### ISSUE TITLE
Usage behind a proxy

### ISSUE THREAD

**Issue by arturo182** [nylas/N1#104]
Hi,

I'm trying to use N1 behind a corporate proxy. I'm using Ubuntu and have both `$http_proxy` and `$https_proxy` set.

I set up my private gmail acount and that part worked, but I cannot send any emails, I get the `"Your draft could not be sent. Please check your connection and try again"` error. I'm also trying to setup Exchange account and I get `"Tunneling socket could not be established, cause=write EPROTO"`.
Also for Exchange, shouldn't there be an option supplying EWS URL?

Thanks!

**Comment by valeriocuscuna** [comment]
+1.
I would like to have the option to manually set proxy / use system settings (reloaded without reloading N1).
Thanks
Valerio

**Comment by sergiokopplin** [comment]
+1

**Comment by toXel** [comment]
+1

**Comment by sergiokopplin** [comment]
it's working after the last update! o//

**Comment by buhe** [comment]
great work!

**Comment by gutenye** [comment]
+1 It's very important for users in China.
@sergiokopplin What are the steps to use it?

**Comment by sergiokopplin** [comment]
@gutenye for me, just the update was enough. Nothing more.

**Comment by sboss** [comment]
+1 this would be great for when people travel to networks that aren't their own and have to work behind a proxy server (like visiting corporate clients).

**Comment by vincihu** [comment]
+1. sock5 proxy

**Comment by tonybenoy** [comment]
+1

**Comment by grinich** [comment]
Sounds like this is fixed so I'm going to close! We generally recommend setting up your OS's networking configuration to use the desired proxy settings.

**Comment by mbilker** [comment]
@grinich World this work for `NylasAPI` requests which are made through the node request module

**Comment by edwinyzh** [comment]
What a pity! I wouldn't be able to use it in China until it supports proxy.

**Comment by mbilker** [comment]
@edwinyzh If you want to implement the feature, you can override the request module to use a proxy.

**Comment by mbilker** [comment]
I don't remember the specifics of the override.

**Comment by bonaldi** [comment]
Can this be reopened, @grinich? Doesn't seem to be fixed, at least for me, and also for some others going by the new tickets @mbilker and others are rolling into this one.

**Comment by lalitkapoor** [comment]
maybe helpful: https://www.npmjs.com/package/global-tunnel

**Comment by bengotow** [comment]
Thanks for the link @lalitkapoor. It looks like that'd do the trick, but we may try to rewrite our HTTP request logic to use XMLHTTPRequest instead of the `request` library. Chromium does some really nice auto-detection of system proxy settings, and we'd like to be able to use that rather than making users provide proxy settings, or trying to read them on each platform ourselves. Stay tuned!

**Comment by msmosso** [comment]
+1 for manually proxy configuration. I'm running N1 on Windows, behind a corporate proxy, and it doesn't reach the api.

**Comment by mbilker** [comment]
This is in development.

**Comment by ex0b1t** [comment]
+1

**Comment by drodmun** [comment]
+1

**Comment by jansestakgooddata** [comment]
Guys, is there any progress? I´m also behind the corporate proxy which makes using this app only a dream.

**Comment by cybertk** [comment]
+1

**Comment by mbilker** [comment]
Currently, if you modify the program to make `node-request` use the proxy and set your system's proxy settings, then it will use the proxy settings. Since a large part of N1 runs in the Electron main process, it cannot use things like `XHRHttpRequest` or `window.fetch` to get resources and follow proxy settings. The main process uses `node-request` which is unaware of system proxy settings and is not specifically designed for Electron usage with proxies.

**Comment by brwolfgang** [comment]
+1

**Comment by brwolfgang** [comment]
You can follow up what is being developed on [Waffle](https://waffle.io/nylas/N1). 
Filter the board using "proxy" to see where it is. Currently there's no one working on it =/

**Comment by cmmata** [comment]
+1

**Comment by jrm06** [comment]
Nylas N1 is great but it's unusable at work. Please, add proxy support. Or maybe you know a software or a tips for Nylas N1 can force proxy.

**Comment by lalitkapoor** [comment]
might be able to get away with something like this on the mac (they have windows version too) https://www.proxifier.com/mac/

**Comment by zaaack** [comment]
+1

**Comment by hallamoore** [comment]
Another request for this: https://nylas.zendesk.com/agent/tickets/3844

**Comment by anxsec** [comment]
@arturo182 on linux, just run with --proxy-server param.

>nylas --proxy-server=socks5://127.0.0.1:1080

**Comment by viveris-villeurbanne** [comment]
@anxsec
* option --proxy-server param does not work for me
* neither does http_proxy and https_proxy correctly set

-> still a proxy problem for me ! (OS Kubuntu 16.04)
Are you guys still facing this proxy problem ?

**Comment by louisrubet** [comment]
+1

Still no progress on that ?

**Comment by jenghung** [comment]
+1

**Comment by wuairc** [comment]
+1, can not use it reliably without proxy for work

**Comment by fffx** [comment]
+1

**Comment by fangxing204** [comment]
It works with [proxychains](http://proxychains.sourceforge.net/)

`$  proxychains nylas  # from terminal`

**Comment by oikonomopo** [comment]
+1

**Comment by m31271n** [comment]
+1

**Comment by nelsonhoover** [comment]
No proxy means it's unusable for me on some networks behind firewalls.

**Comment by ConeyLiu** [comment]
Any update on this ?

**Comment by NoZiL** [comment]
+1

**Comment by Cris70** [comment]
I'm having this problem too, I think.
When I try to add an Office365 account, it wait for a few seconds with the "Adding account..." caption on the button, the it stops and shows a red message: "Greeting never received".
However, I know the account works because I can connect without problems with Wavebox.

This is what I get in the log file:
```
{"host":"xmper8q3.gcv.dom","timestamp":"2017-07-05T11:10:12.734Z","payload":"Error\n    at new APIError (/src/flux/errors.es6:57:19)\n    at Request._callback (/src/flux/nylas-api-request.es6:75:26)\n    at Request.self.callback (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:1081:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:1001:12)\n    at IncomingMessage.g (events.js:286:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"}
{"host":"xmper8q3.gcv.dom","timestamp":"2017-07-05T11:10:12.737Z","payload":{"fingerprint":["{{ default }}","api error","http://localhost:2578/auth",500,"Greeting never received"],"rateLimit":{"ratePerHour":30,"key":"APIError:http://localhost:2578/auth:500:Greeting never received"},"pluginIds":[]}}
{"host":"xmper8q3.gcv.dom","timestamp":"2017-07-05T11:10:12.764Z","payload":"{ Error\n    at new APIError (/src/flux/errors.es6:57:19)\n    at Request._callback (/src/flux/nylas-api-request.es6:75:26)\n    at Request.self.callback (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:1081:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:1001:12)\n    at IncomingMessage.g (events.js:286:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)\n  name: 'APIError',\n  error: null,\n  body: { message: 'Greeting never received', type: 'api_error' },\n  requestOptions: \n   { url: 'http://localhost:2578/auth',\n     method: 'POST',\n     json: true,\n     timeout: 180000,\n     path: '/auth',\n     body: \n      { provider: 'office365',\n        email: 'guadagnino.cristiano@AMENDEDt',\n        name: 'Cristiano Guadagnino',\n        settings: [Object] } },\n  statusCode: 500,\n  message: 'Greeting never received',\n  errorType: 'api_error' } { pluginIds: [] }\n"}
{"host":"xmper8q3.gcv.dom","timestamp":"2017-07-05T11:10:13.028Z","payload":"undefined\n"}
{"host":"xmper8q3.gcv.dom","timestamp":"2017-07-05T11:10:13.029Z","payload":"undefined\n"}
{"host":"xmper8q3.gcv.dom","timestamp":"2017-07-05T11:10:13.029Z","payload":"undefined\n"}
```
I tried to proxify nylas-mail with proxychains-ng but it did not work (nylas-mail or proxychains hangs).

Any suggestion?

TIA
Cris

**Comment by Cris70** [comment]
Instead of using the proxychains-ng executable available in openSUSE's repos (which is v4.11), I compiled it myself (v4.12).

proxychains-ng itself worked ok after compiling my private copy, but nylaa-mail did not.

Apparently nylas-mail is always trying to connect to this address: http://localhost:2578/auth, which does not seems correct to me.
It is doing this both when I launch it alone and when I proxify it through proxychains-ng.

Any ideas?

TIA
Cris

**Comment by Cris70** [comment]
Replying to myself: adding `localnet 127.0.0.0/255.0.0.0` to my proxychains.conf file made nylas-mail work!!

**Comment by karnikram** [comment]
Not able to get it to work through proxychains. Can anyone help?

**Comment by unkemptArc99** [comment]
+1

**Comment by livc** [comment]
@fffx awesome!! it works.

**Comment by livc** [comment]
Sorry, in my situation, it only can log into Gmail but can not send emails with `proxychains`.

**Comment by Cris70** [comment]
@livc are you sure you cannot?
In my case, sending takes a long time (about a minute) but in the end it succeeds.
Don't know why it takes so long, though.

**Comment by rothn** [comment]
I can't use nylas at all -- I have the http_proxy, https_proxy, and no_proxy env vars set properly in my environment. No matter what I try to configure, it fails with some type of error. For GMail it says "Could not establish tunneling socket"
