### ISSUE TITLE
Syncing mailbox error

### ISSUE THREAD

**Issue by Trindaz** [nylas/N1#1170]
Version: 0.3.45-3b5880e (0.3.45-3b5880e)
Platform: OS X Yosemite 10.10.3 (14D136)
Email account: GMail

I am running the open source Sync Engine locally at commit 56f297d. I was able to authenticate my account and start the sync process. I was able to use the API to add my account to the Nylas config file. When I open N1 I can see my account already selected. In the bottom right it says "An error occurred while syncing your mailbox.". The API reports an error with this stack trac
```
Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
	  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
	  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
	NotFound: 404: Not Found
```

Is my version of N1 out of sync with the version of sync-engine I am running?

**Comment by mbilker** [comment]
Report this bug at [nylas/sync-engine](https://github.com/nylas/sync-engine).
