### ISSUE TITLE
Fix build modules for FreeBSD

### ISSUE THREAD

**Issue by forquare** [nylas/N1#1176]
`%>uname -a
FreeBSD fbsd-dtop 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64`

```
%>script/bootstrap
Node: v5.2.0
npm: v2.14.7

---> Installing N1 build tools
     This goes inside the `build` folder and runs `nam install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `nam`.
     Everything else needs to be compiled against Chromium with `app`.

     $ npm --userconfig="/tmp/N1/.npmrc" install --loglevel error --cwd=/tmp/N1/build --ignoreStdout=true 


Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2756, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1501, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'deps/breakpad/breakpad.gyp:dump_syms#target'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System FreeBSD 10.2-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/N1/build/node_modules/minidump
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! FreeBSD 10.2-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig=/tmp/N1/.npmrc" "install" "--loglevel" "error"
npm ERR! node v5.2.0
npm ERR! nam  v2.14.7
npm ERR! code EBADPLATFORM

npm ERR! not sup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: csslint@0.9.10
npm ERR! notsup Valid OS:    darwin,linux,win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   freebsd
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/N1/build/npm-debug.log
```

**Comment by mbilker** [comment]
Thanks for the report @forquare. It appears the `csslint` package is not compatible with FreeBSD. This is not specific to N1. I found that `csslint@0.10.0` removed the `os` parameter. N1 needs to update its `grunt-contrib-csslint` package to fix this error.

**Comment by mbilker** [comment]
The `platform-linux` tag is to classify this issue as not Windows or OS X.

**Comment by mbilker** [comment]
@forquare PR #1177 was merged in. Could you retry the build using the latest `HEAD` of the `master` branch?

**Comment by forquare** [comment]
Having had a quick look during lunch, it appears to generate the same error.  I will try again later though when I have more time to test.

**Comment by mbilker** [comment]
Make sure you run `script/clean` to erase the already installed node modules so `script/bootstrap` will fetch new versions. Do a `git pull` to get the latest changes from the git repository.

**Comment by forquare** [comment]
Alas, it appears to still want `csslint@0.9.10`:

```
%>script/bootstrap          
Node: v5.2.0
npm: v2.14.7

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/usr/home/benlavery/N1/.npmrc" install --loglevel error --cwd=/usr/home/benlavery/N1/build --ignoreStdout=true 

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2756, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1501, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'deps/breakpad/breakpad.gyp:dump_syms#target'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System FreeBSD 10.2-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/benlavery/N1/build/node_modules/minidump
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! FreeBSD 10.2-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig=/usr/home/benlavery/N1/.npmrc" "install" "--loglevel" "error"
npm ERR! node v5.2.0
npm ERR! npm  v2.14.7
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: csslint@0.9.10
npm ERR! notsup Valid OS:    darwin,linux,win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   freebsd
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/benlavery/N1/build/npm-debug.log
```

I’m not sure where this is coming from, doing a `grep -r "0\.9\.10" *` only returns matches in change logs…

This time I have also attached my `nom-debug.log` file.

[npm-debug.log.zip](https://github.com/nylas/N1/files/121466/npm-debug.log.zip)

**Comment by forquare** [comment]
I've had a crack at this again with a clean install of FreeBSD 10.3, but it is still failing in the same way.  From my understanding, @mbilker introduced a change which should have bumped `csslint` to 0.10.0, but something is still trying to use 0.9.10.

**Comment by jackiehluo** [comment]
Hey! Closing for now because supporting this version isn't really in the scope of our project—but let us know if we can help with anything!
