### ISSUE TITLE
Build on Ubuntu 15.04 fails

### ISSUE THREAD

**Issue by vass-david** [nylas/N1#14]
```shell
➜  N1 git:(master) ./script/bootstrap 
Node: v0.12.6
npm: v2.11.2

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig=/home/david/Sources/N1/.npmrc install --loglevel error --cwd=/home/david/Sources/N1/build --ignoreStdout=true 



---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ /home/david/Sources/N1/build/node_modules/.bin/npm --userconfig=/home/david/Sources/N1/.npmrc install --loglevel error --cwd=/home/david/Sources/N1/apm --ignoreStdout=true 

child_process: customFds option is deprecated, use stdio instead.
Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gnome-keyring-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gnome-keyring-1' found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/david/Sources/N1/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-30-generic
gyp ERR! command "node" "/home/david/Sources/N1/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/david/Sources/N1/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
npm ERR! keytar@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@2.1.0 install script.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-30-generic
npm ERR! command "node" "/home/david/Sources/N1/build/node_modules/.bin/npm" "--userconfig=/home/david/Sources/N1/.npmrc" "install" "--loglevel" "error"
npm ERR! cwd /home/david/Sources/N1/apm
npm ERR! node -v v0.12.6
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by justinnichols** [comment]
Run `sudo apt-get install libgnome-keyring-dev`

That fixed it for me.

**Comment by vass-david** [comment]
Great, thanks.

Now I see this error:
```shell
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/david/Sources/N1/apm/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/david/Sources/N1/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/home/david/Sources/N1/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Is this related to https://github.com/nylas/N1/issues/12 ? My node version is 0.12.6.

**Comment by justinnichols** [comment]
I would advise installing nvm and then using nvm to install version 0.10.40 of nodejs.  It seems that is what worked well for me.

**Comment by bengotow** [comment]
Hi @vass-david—sorry for the hassle. Our build scripts currently require Node 0.10.x, and we haven't had a chance to update them. I've added a note to CONTRIBUTING.md. `nvm` is definitely the way to go so that you don't need to uninstall the version of Node you currently have.
