### ISSUE TITLE
"Can't create Snooze category" error

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1556]
![image](https://cloud.githubusercontent.com/assets/547354/13505753/785c7eb4-e12f-11e5-8aa3-e0b9f4b56c2a.png)

**Comment by bengotow** [comment]
Thanks for reporting this Jeff—do you know if that account has a  folder / label called `N1-Snoozed` when you view it in other apps?

**Comment by jweinstein** [comment]
2 accounts, both have it:

![image](https://cloud.githubusercontent.com/assets/547354/13506998/89dcd278-e135-11e5-8810-d8252715d975.png)

and 

![image](https://cloud.githubusercontent.com/assets/547354/13507014/9c30dd8e-e135-11e5-9219-d1c1302629d1.png)

**Comment by jstejada** [comment]
hey @jweinstein thanks for the details. Were you able to use Snooze before this? did something specific trigger the issue? Or is this the first time you tried to use it and just threw the error?

Thanks!

**Comment by jweinstein** [comment]
I think it was time #1 but not 100% sure.

> On Mar 3 2016, at 1:51 pm, Juan &lt;notifications@github.com&gt; wrote:  

>

> hey [@jweinstein](https://github.com/jweinstein) thanks for the details.
Were you able to use Snooze before this? did something specific trigger the
issue? Or is this the first time you tried to use it and just threw the error?

>

> Thanks!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1556#issuecomment-191981096).![](https://github.com/notifications/bea
con/AAhaGqyx-WxUF9q4q3URV6fGunrimWnYks5pp1f9gaJpZM4HoucH.gif)

**Comment by jstejada** [comment]
hmm, I see, thanks! if you open the activity window, can you send me the error returned by the API?
thanks!

**Comment by jweinstein** [comment]
Seems to be working now. Can't reproduce the issue :(

> On Mar 6 2016, at 5:12 pm, Juan &lt;notifications@github.com&gt; wrote:  

>

> hmm, I see, thanks! if you open the activity window, can you send me the
error returned by the API?  
thanks!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1556#issuecomment-193029093).![](https://github.com/notifications/bea
con/AAhaGkUYu_954gWS_125Qopcb7_ZhHL0ks5pq3tzgaJpZM4HoucH.gif)

**Comment by jstejada** [comment]
ok thanks @jweinstein. I'm going to close this for now, if this happens again, let me know what error pops out in the activity window. Thanks!

**Comment by myovchev** [comment]
Hi, I experience the same issue and it looks like insufficient permissions. I have just installed N1 via the .deb package (v0.4.14-53cd69b) on Ubuntu 15.10. I'm attaching the logs from the developer tools. It also looks like application logs cannot be created in the /tmp folder.

[n1.log.txt](https://github.com/nylas/N1/files/170926/n1.log.txt)

**Comment by 5imple** [comment]
I'm facing the same issue

**Comment by 5imple** [comment]
logs:

Error: Could not create Snooze category
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/thread-snooze/lib/snooze-utils.js:56:31
From previous event:
    at ModelQuery.then (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/models/query.js:203:29)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/thread-snooze/lib/snooze-utils.js:52:8
From previous event:
    at Object.createSnoozeCategory (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/thread-snooze/lib/snooze-utils.js:50:60)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/thread-snooze/lib/snooze-utils.js:84:26
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.getSnoozeCategory (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/thread-snooze/lib/snooze-utils.js:78:6)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/thread-snooze/lib/snooze-utils.js:92:53
    at Array.forEach (native)
    at getSnoozeCategoriesByAccount (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/thread-snooze/lib/snooze-utils.js:90:14)
    at new SnoozeStore (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/thread-snooze/lib/snooze-store.js:18:36)
    at Object.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/thread-snooze/lib/main.js:9:22)
    at Package.module.exports.Package.activateNow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:295:27)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:280:28
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:189:15)
    at Package.module.exports.Package.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:274:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:605:21)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:579:29
    at Config.module.exports.Config.transact (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/config.js:372:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:568:23)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:551:46)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:738:34

**Comment by jstejada** [comment]
@jweinstein, @myovchev a fix is in progress, you can follow the conversation in #1676

**Comment by mixpack** [comment]
I'm also having this error. I do not have the snooze folders/labels or what its called. Where can I create/view those?
