### ISSUE TITLE
TypeError: Cannot read property 'pluginIds' of undefined

### ISSUE THREAD

**Issue by aliceinwire** [nylas/N1#1785]
##### Are there any related issues?

not found

##### What operating system are you using?
Gentoo

##### What version of N1 are you using?
0.4.5-b0ec335

**Bug?**
##### Do you have any third-party plugins installed?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

```
Streaming log data to /tmp/Nylas-N1-17041.log
App load time: 183ms
/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:130
    if (extra.pluginIds && extra.pluginIds.length > 0) {
             ^

TypeError: Cannot read property 'pluginIds' of undefined
    at ErrorReporter.module.exports.ErrorReporter._prepareSentryCaptureObjects (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:130:14)
    at ErrorReporter.module.exports.ErrorReporter.reportError (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:60:27)
    at ErrorLogger.module.exports.ErrorLogger._notifyExtensions (/usr/share/nylas/resources/app.asar/src/error-logger.js:219:26)
    at ErrorLogger.module.exports.ErrorLogger.reportError (/usr/share/nylas/resources/app.asar/src/error-logger.js:60:10)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)
```

**Comment by mbilker** [comment]
This issue is fixed in the newer version
