### ISSUE TITLE
[config-help] What am I doing wrong?

### ISSUE THREAD

**Issue by sg-s** [nylas/N1#185]
Hi, I'm trying to set up the sync-engine and N1 to work locally. 

* I've followed the instructions [here](https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine) to set up sync-engine
* I think the sync-engine seems to be working fine, this is what I see in `http://localhost:5555/accounts`:

```
[
    {
        "account_id": "my-account-id",
        "email_address": "me@gmail.com",
        "id": "same-as-account-id",
        "name": "My Name",
        "object": "account",
        "organization_unit": "label",
        "provider": "gmail",
        "sync_state": "running"
    }
]
```

* This is what my ~/.nylas/config.cson file looks like:

```

"*":
  invitationCode: "my-invitation-code"
  updateIdentity: "some-long-string"
  env: "local"
  nylas: 
    accounts: [
      {
          "account_id": "my-account-id",
          "email_address": "me@gmail.com",
          "id": "my-account-id",
          "name": "My Name",
          "object": "account",
          "organization_unit": "label",
          "provider": "gmail",
          "sync_state": "running"
      }
    ]
    accountTokens:
        my-account-id: "my-account-id"
```
    
However, with this, when I start N1, it doesn't seem to read any of this, and starts at the welcome screen (and even asks me for an invitation code)

When I remove the last line (accountTokens...), it jumps straight to the account I configured, but says it is syncing, but doesn't actually do anything.

Any help appreciated!

**Comment by bengotow** [comment]
Hey! It sounds like the app is failing to parse your config.cson. The format is pretty particular and white space sensitive. We're actually thinking about moving to JSON - the cson is something the project inherited from JSON. 

Can you try removing the parenthesis and braces from your config file? That may fix the parsing issue.

**Comment by sg-s** [comment]
@bengotow i think this is it ... but i can't figure out where the parse is failing. should i use tabs or spaces to indent? tried removing braces and brackets but it doesn't seem to work...

**Comment by sg-s** [comment]
i think I have it parse correclty now. i have modified the end to:

```
accountTokens: [
   {
        "my-account-id": "my-account-id"
   }
]
```
and when I load N1 it goes straight to the account, but it still says "syncing", but doesn't actually do anything.

**Comment by jieyanhuang** [comment]
@sg-s, I ran into the same problem. I think the issue was with mixed tabs and whitespace. Go with spaces!

**Comment by sg-s** [comment]
@jieyanhuang thanks! I think I solved the parsing issue too -- it goes to my account, but refuses to sync. does it work for you?

**Comment by hrwebasst** [comment]
I have the same issue too, syncing never seems to do anything, also had to add brackets around accountTokens otherwise it said there was a problem syncing.

**Comment by Fryie** [comment]
Having a hard time here too. Double-checked the syntax and whitespaces and tried multiple variants, but N1 always goes to the onboarding screen.

**Comment by Proplex** [comment]
I'm also having this problem, N1 seems stuck in a "Syncing your mailbox" phase after editing my config to point to my local server.

There's an error thrown in the log, which is as follows:

```
APIError: Cannot make Nylas request for account <my account id> auth token.
    (No stack trace)
From previous event:
    at JSONBlobQuery.ModelQuery.then (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/models/query.js:203:29)
    at new NylasSyncWorker (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-sync-worker.js:78:73)
    at NylasSyncWorkerPool.workerForAccount (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-sync-worker-pool.js:51:16)
    at __bind (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-sync-worker-pool.js:3:61)
    at Function._.map._.collect (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/underscore/underscore.js:172:24)
    at NylasSyncWorkerPool._onAccountsChanged (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-sync-worker-pool.js:30:19)
    at new NylasSyncWorkerPool (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-sync-worker-pool.js:21:12)
    at Object.module.exports.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/main.js:9:14)
    at Package.module.exports.Package.activateNow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:285:27)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:270:28
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:179:15)
    at Package.module.exports.Package.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:264:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:582:21)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:556:29
    at Config.module.exports.Config.transact (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/config.js:372:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:545:23)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:528:46)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startSecondaryWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:783:21)
    at Object.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/window-secondary-bootstrap.js:20:12)
    at Object.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/window-secondary-bootstrap.js:31:4)
    at Module._compile (module.js:434:26)
    at Object.keys.forEach.Object.defineProperty.value [as .js] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js:67:3)
    at window.onload (file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js:107:5)module.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:318(anonymous function) @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:282module.exports.CapturedTrace.fireRejectionEvent @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/captured_trace…:220module.exports.Promise._notifyUnhandledRejection @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/debuggability.…:40Async._drainQueue @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:128Async._drainQueues @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:135global.drainQueues @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15processImmediate @ timers.js:374
```

My config is as follows:

```
"*":
  env: "local"
  core:
    disabledPackages: [
      "quick-schedule"
      "composer-templates"
      "composer-translate"
      "message-view-on-github"
      "personal-level-indicators"
      "phishing-detection"
      "github-contact-card"
    ]
    disabledPackagesInitialized: true
  updateIdentity: "my_update_identity"
  nylas:
    accounts: [
      {
        account_id: "my_actual_id"
        email_address: "my_actual_email"
        id: "my_actual_id"
        name: ""
        object: "account"
        organization_unit: "folder"
        provider: "custom"
        sync_state: "running"
      }
    ]
    mailto:
      "prompted-about-default": true
  accountTokens:
    "my_actual_id": "my_actual_id"
  devMode: true
```

Any ideas? The API server I have running doesn't get any hits when N1 is launched.

**Comment by Analect** [comment]
@Proplex
I was having problems too .. but realised I was missing `server_id: "my_actual_id"` from the accounts section .. so you should have all three id, account_id and server_id set to the value for "my_actual_id".

Also, N1 complained that `accountTokens:  "my_actual_id": "my_actual_id"` should be on the same line.  Hopefully this helps.

**Comment by Proplex** [comment]
@Analect 
I've tried both of your suggestions and it doesn't seem to be working, still. Would you mind posting your actual config that's working? I'd really love to try N1, but for some reason this config has me completely bogged down.

**Comment by Analect** [comment]
@Proplex 
So I have:

```
"*":
  env: "local"
  core:
    disabledPackages: [
      "quick-schedule"
      "composer-templates"
      "composer-translate"
      "message-view-on-github"
      "personal-level-indicators"
      "phishing-detection"
      "github-contact-card"
    ]
    disabledPackagesInitialized: true
  nylas:
    accounts: [
      {
        server_id: "long-string-acc-id"
        account_id: "long-string-acc-id"
        email_address: "my_email@gmail.com"
        id: "same as long-string acc id above"
        name: "My name"
        object: "account"
        organization_unit: "label",
        provider: "gmail"
     }
    ]
    accountTokens: "same as acc id above": "same as acc id above"
```
Maybe check that it hasn't put a cached version of *wrong* config under `~/.nylas/compile-cache` folder ... 
Also, I'm running my sync-engine on `localhost:5555` and therefore don't include any explicit `syncEngine` setting.
Finally, perhaps run up N1 from the command-line .. and any problems with the config will be more apparent. `/usr/share/nylas/nylas`

On peaking into my config file with the system up and running .. I can now see that N1 has appended more stuff (see below) automatically to the bottom of my file ... not altogether sure why ... 

```
"acc_id again":
      cursor: "long string"
  updateIdentity: "new long string"
```

**Comment by Proplex** [comment]
@Analect Huzzah! It works. I cleared my compile-cache and updated my own config to look similar to yours, and now everything syncs beautifully. Thanks for your help.

**Comment by Analect** [comment]
Glad to hear it.

**Comment by jstejada** [comment]
closing this issue for now. feel free to reopen if you have any further questions.
