### ISSUE TITLE
Outlook doesn't sync past specific point

### ISSUE THREAD

**Issue by cuddylier** [nylas/N1#1868]
##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.19

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Outlook

Outlook does not sync past a specific date, in my case the 31st March. I have tried uninstalling Nylas along with deleting the .nylas folder and doing a full re-install then re-adding the Outlook account and syncing again however it only syncs all emails before this date and none of the latest.

**Comment by mattjdev** [comment]
I am having the same issues on OS X El Capitan 10.11.3 using Nylas v0.4.19-d41e72c

**Comment by koyuawsmbrtn** [comment]
Same here under Windows 10 Insider Build 14295 x64. No third-party plugins installed, seems to happen with Outlook provider. My folders are blank...

**Comment by jstejada** [comment]
Hi all, could you email support@nylas.com with the email address of the affected account so we can look into it? Thanks!

**Comment by cuddylier** [comment]
@jstejada I did on the 3rd April but haven't received any response, mine has since started working again but no doubt it'll stop again, maybe they can check my logs from when I was experiencing the issue to see what maybe was going wrong.

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3592

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3066

**Comment by jackiehluo** [comment]
Another incidence: https://github.com/nylas/N1/issues/1868

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3736

**Comment by jackiehluo** [comment]
Another incidence: https://twitter.com/laurentupit/status/750771058068877313

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3997

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4409

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4400

**Comment by hallamoore** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4450

**Comment by hallamoore** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3913

**Comment by hallamoore** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3998

**Comment by annielcook** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4737

**Comment by annielcook** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4548

**Comment by Ehekatl** [comment]
+1 for this issue, I can send email but all folders are empty

**Comment by hallamoore** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4975

**Comment by hallamoore** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4080

This one is particularly interesting. The sync problem started when the user deleted an "Archive" folder from Outlook's Deleted Items folder, and resolved itself when they created a new folder in the same spot with the same name.

**Comment by FerranBueno** [comment]
Hi guys, do to this unexpected problem with _hotmail syncing_ I am forced to give up and move to another email client. Such a pitty! 
Hopefully we'll see us again in the future. Until then, all the best with your work and effort!

**Comment by toddsjsimmer** [comment]
hi, i cleaned my mailbox on gmail July 4th and i have about 12 Gb's of email. I've reinstalled Nylas on several systems and it's still show July 4th as the last time it was updated. i also updated to pro. i can see it doing curl request for updates but i'm not seeing an update. can you guys reset my account?

**Comment by PrestadorMinutoDev** [comment]
No updates for my exchange account too! It has just stopped. Linux Manjaro.

**Comment by bricem** [comment]
Same things here. All stuck whichever is the platform I use: Mac or Windows 10.

**Comment by Lampwick** [comment]
Same problem with exchange under Antergos.

**Comment by jaap** [comment]
Same here. Not syncing anymore.

**Comment by ashhole** [comment]
Same problem, started this morning. No change that I know of since yesterday.

**Comment by jaap** [comment]
@ashole patience solved it for me :)

**Comment by meymeynard** [comment]
I had the same problem. New emails does not sync in. I already re-authenticated with GMail and tried removing the account and adding it again. But it still does not sync.

I'm using a macOS Sierra v10.12.1 by the way. 

Thanks!

**Comment by yogipatel5** [comment]
I am not sure what the resolution is, I am on Mac Sierra v10.12.1 and the sync is very spotty, I have tried to remove and add the account along with reathenticating and it syncs and then goes out of sync again. 

Can't believe its almost 2017 and still don't have a reliable mail client.

**Comment by Ehekatl** [comment]
can you guys have a priority label like `critical` for this ? @bengotow 
can't believe you have develop so many features and new plugins but leave such an important bug for more than half year.

**Comment by evertsemeijn** [comment]
Same situation here since Dec 7. Creating support ticket doesn't help as well.

**Comment by adriantombu** [comment]
Same here since yesterday. Partial sync, and one SMTP account does not sync at all. No problem on Spark that I have to use as backup...

**Comment by americanmoss** [comment]
Experiencing the same issue as of 1/14. Did anyone ever come up with a fix for this?

**Comment by jtflynnz** [comment]
I am also experiencing this with 2 gmail accounts, one imap account, and one outlook.com account. Relaunching app, re-authenticating, and using the developer "Reload" option is not working for me. Aso of 2/8/2017 this is my "newest" fetched email:

![image](https://cloud.githubusercontent.com/assets/5449443/22754155/8b7ace16-ee0c-11e6-9c7c-b792a800933c.png)

**Comment by louim** [comment]
I am experiencing the same problem. Date is Feb 7 for me on an hotmail account. Worked correctly in Nylas Pro, I recently switched to Nylas Mail. Tried to Remove and add back the account.

Looked in the console for errors, havent seen any. Activity show sync seems to be working correctly:
<img width="299" alt="capture d ecran 2017-02-14 a 11 09 40" src="https://cloud.githubusercontent.com/assets/923718/22937413/8d3a2730-f2a6-11e6-973d-898db05030f4.png">

Is there something else I can do to debug this?

**Comment by jstejada** [comment]
thanks for the info! can you follow the steps in https://github.com/nylas/nylas-mail/issues/3232#issuecomment-275729794?

If its the same issue I'll merge this into #3232

**Comment by louim** [comment]
@jstejada I read trough @3232, and it doesn't seem to be the same issue. I see no errors at all in the  activity window console, and no "syncing mailboxes" notification at the bottom of the sidebar. The initial sync completed and emails worked for my hotmail account for a couple of days before stopping. Both my gmail accounts are still working correctly.

![capture d ecran 2017-02-15 a 16 26 07](https://cloud.githubusercontent.com/assets/923718/22996308/5b5672b8-f39c-11e6-961b-06b32b05ee30.png)
![capture d ecran 2017-02-15 a 16 25 55](https://cloud.githubusercontent.com/assets/923718/22996309/5b69776e-f39c-11e6-8cbd-ae1cf552156c.png)

**Comment by jstejada** [comment]
Hmm, interesting. Restarting the app has no effect?

**Comment by louim** [comment]
No effect.

**Comment by monkeydri** [comment]
Same error with custom IMAP account (mail.com) , my emails used to be synced OK but since few days I do not see any new mails anymore. No error shown in the Activity window, it looks like Nylas Mail thinks it's up to date. I have multiple email accounts in Nylas (all custom IMAP) and only one is experiencing this problem (mail.com). 

Interestingly I had the same problem in the past with the same account with older version of Nylas N1 + custom sync engine. I thought the problem was solved by switching to Nylas Mail, but apparently not. 

I think resetting the email cache database will fix this but it's cumbersome and I'm pretty sure the problem will appear again.


- operating system : Mac - Sierra OS 10.12.3
- Nylas Mail version : v1.0.26. did have the same problem with Nylas N1 and custom sync-engine.
- third-party plugins installed : none
- issue related to a specific email provider : happens only on my mail.com account (IMAP). I have other IMAP accounts with a different provider and emails are synced correctly.
- issue reproducibility : I don't know the cause of this bug as it used to work alright.

**Comment by louim** [comment]
Some news: An hour ago, Nylas Mail decided it wasn't able to authenticate my hotmail account. 
<img width="237" alt="capture d ecran 2017-02-23 a 14 25 21" src="https://cloud.githubusercontent.com/assets/923718/23275296/ff273980-f9d3-11e6-9da4-8d3c354c5dbe.png">

I'm using two factor auth, so I have an application password set up for Nylas. It obviously hasn't changed since I created it. Using the "Check again" button does not resolve the problem. Nor does restarting Nylas.

This is the error that is going on in loop since then in the activity console.
```
breadcrumbs.js:53 <myemail@hotmail.com> 🔃  SyncWorker: Errored while syncing account IMAPAuthenticationError: Error in sync loop: Error: LOGIN failed.
    at NylasError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:2:1)
    at IMAPAuthenticationError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/imap-errors.js:16:1)
    at convertImapError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/imap-errors.js:109:15)
    at Connection._imap.once.err (imap-connection.es6:178:16)
    at Connection.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at reentry (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:1610:12)
    at Connection.checkCaps (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:1635:22)
    at Connection._resTagged (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:1535:22)
    at Parser.<anonymous> (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:179:10)
    at Parser._parse (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:143:16)
    at Parser._tryread (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:86:15)
    at TLSSocket.Parser._cbReadable (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:57:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at TLSWrap.onread (net.js:543:20)
    at Socket.ondata (_stream_wrap.js:58:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:543:20) (anonymous function) @ breadcrumbs.js:53
```

**Comment by monkeydri** [comment]
same error on 1.0.29

**Comment by jstejada** [comment]
Thanks for the additional details! We are going to look into this

**Comment by monkeydri** [comment]
problem still there with Nylas Mail v1.0.30

**Comment by monkeydri** [comment]
problem still there with Nylas Mail v1.0.45

**Comment by mfiume** [comment]
And v1.0.48

**Comment by jstejada** [comment]
Thanks for the updates! This should be fixed in our upcoming Nylas Mail release.
