### ISSUE TITLE
Stuck "loading" when opening an email

### ISSUE THREAD

**Issue by 1beb** [nylas/N1#1881]
Stuck here, no matter what conversation I try to click on: 

![stuck-loading](https://cloud.githubusercontent.com/assets/421859/14286910/67b6f732-fb16-11e5-9dc3-3199a49da7f3.jpg)

##### What operating system are you using?

Ubuntu 15.10 64 bit

##### What version of N1 are you using?

0.4.19-d41e72c

**Bug?**

Probably. From debug logs: 

```
{"host":"monster","timestamp":"2016-04-05T15:01:35.641Z","payload":["0: SELECT `Message`.`data`, IFNULL(`MessageBody`.`value`, '!NULLVALUE!') AS `body`  FROM `Message` LEFT OUTER JOIN `MessageBody` ON `MessageBody`.`id` = `Message`.`id` WHERE `Message`.`thread_id` = 'en6hrom9m96yplsodwz7djv7i'  ORDER BY `Message`.`date` ASC "]}
{"host":"monster","timestamp":"2016-04-05T15:01:35.688Z","payload":"TypeError: Cannot read property 'format' of undefined\n    at Object.module.exports.Utils.fullTimeString (/usr/share/nylas/resources/app.asar/src/flux/models/utils.js:73:45)\n    at MessageTimestamp.render (/usr/share/nylas/resources/app.asar/internal_packages/message-list/lib/message-timestamp.js:45:24)\n    at MessageTimestamp.render (/usr/share/nylas/resources/app.asar/internal_packages/message-list/lib/message-timestamp.js:3:61)\n    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:789:34)\n    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:816:14)\n    at [object Object].wrapper [as _renderValidatedComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:237:30)\n    at [object Object].wrapper [as mountComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:192:44)\n    at ReactDOMComponent.Mixin._createContentMarkup (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:289:32)\n    at ReactDOMComponent.Mixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:199:12)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)\n    at [object Object].wrapper [as mountComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:192:44)\n    at ReactDOMComponent.Mixin._createContentMarkup (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:289:32)\n    at ReactDOMComponent.Mixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:199:12)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)\n    at [object Object].wrapper [as mountComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:192:44)\n    at ReactDOMComponent.Mixin._createContentMarkup (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:289:32)\n    at ReactDOMComponent.Mixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:199:12)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)\n    at [object Object].wrapper [as mountComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:192:44)\n    at ReactDOMComponent.Mixin._createContentMarkup (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:289:32)\n    at ReactDOMComponent.Mixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:199:12)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)\n    at [object Object].wrapper [as mountComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:192:44)\n    at ReactDOMComponent.Mixin._createContentMarkup (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:289:32)\n    at ReactDOMComponent.Mixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:199:12)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)\n    at [object Object].wrapper [as mountComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)\n    at [object Object].wrapper [as mountComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at [object Object].ReactCompositeComponentMixin.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)\n    at [object Object].wrapper [as mountComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at Object.ReactReconciler.mountComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)\n    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:400:40)\n    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:306:16)\n    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251:14)\n    at ReactDOMComponent.Mixin._updateDOMChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470:12)\n    at ReactDOMComponent.Mixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319:10)\n    at ReactDOMComponent.Mixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:748:23)\n    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)\n    at [object Object].ReactCompositeComponentMixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)\n    at [object Object].wrapper [as updateComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:506:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at Object.ReactChildReconciler.updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:83:25)\n    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277:47)\n    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251:14)\n    at ReactDOMComponent.Mixin._updateDOMChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470:12)\n    at ReactDOMComponent.Mixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319:10)\n    at ReactDOMComponent.Mixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:748:23)\n    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)\n    at [object Object].ReactCompositeComponentMixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)\n    at [object Object].wrapper [as updateComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:506:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at Object.ReactChildReconciler.updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:83:25)\n    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277:47)\n    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251:14)\n    at ReactDOMComponent.Mixin._updateDOMChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470:12)\n    at ReactDOMComponent.Mixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319:10)\n    at ReactDOMComponent.Mixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:748:23)\n    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)\n    at [object Object].ReactCompositeComponentMixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)\n    at [object Object].wrapper [as updateComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:506:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:748:23)\n    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)\n    at [object Object].ReactCompositeComponentMixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)\n    at [object Object].wrapper [as updateComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:506:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at Object.ReactChildReconciler.updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:83:25)\n    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277:47)\n    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251:14)\n    at ReactDOMComponent.Mixin._updateDOMChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470:12)\n    at ReactDOMComponent.Mixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319:10)\n    at ReactDOMComponent.Mixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:748:23)\n    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)\n    at [object Object].ReactCompositeComponentMixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)\n    at [object Object].wrapper [as updateComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:506:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at Object.ReactChildReconciler.updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:83:25)\n    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277:47)\n    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251:14)\n    at ReactDOMComponent.Mixin._updateDOMChildren (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470:12)\n    at ReactDOMComponent.Mixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319:10)\n    at ReactDOMComponent.Mixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:748:23)\n    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)\n    at [object Object].ReactCompositeComponentMixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)\n    at [object Object].wrapper [as updateComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:506:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:748:23)\n    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)\n    at [object Object].ReactCompositeComponentMixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)\n    at [object Object].wrapper [as updateComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:506:10)\n    at Object.ReactReconciler.receiveComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)\n    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:748:23)\n    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)\n    at [object Object].ReactCompositeComponentMixin.updateComponent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)\n    at [object Object].wrapper [as updateComponent] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:539:12)\n    at Object.ReactReconciler.performUpdateIfNecessary (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactReconciler.js:115:22)\n    at runBatchedUpdates (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactUpdates.js:151:21)\n    at ReactReconcileTransaction.Mixin.perform (/usr/share/nylas/resources/app.asar/node_modules/react/lib/Transaction.js:134:20)\n    at ReactUpdatesFlushTransaction.Mixin.perform (/usr/share/nylas/resources/app.asar/node_modules/react/lib/Transaction.js:134:20)\n    at ReactUpdatesFlushTransaction.assign.perform (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactUpdates.js:95:38)\n    at Object.flushBatchedUpdates (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactUpdates.js:175:19)\n    at Object.wrapper [as flushBatchedUpdates] (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)\n    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/usr/share/nylas/resources/app.asar/node_modules/react/lib/Transaction.js:207:25)\n    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/usr/share/nylas/resources/app.asar/node_modules/react/lib/Transaction.js:148:16)\n    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)\n    at Object.enqueueUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactUpdates.js:215:22)\n    at enqueueUpdate (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:30:18)\n    at Object.ReactUpdateQueue.enqueueSetState (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:208:5)\n    at MessageList.ReactComponent.setState (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactComponent.js:69:20)\n    at MessageList._onChange (/usr/share/nylas/resources/app.asar/internal_packages/message-list/lib/message-list.js:563:19)\n    at MessageStore.<anonymous> (/usr/share/nylas/resources/app.asar/internal_packages/message-list/lib/message-list.js:3:61)\n    at EventEmitter.eventHandler (/usr/share/nylas/resources/app.asar/src/flux/modules/reflux-coffee.js:206:27)\n    at emitOne (events.js:82:20)\n    at EventEmitter.emit (events.js:169:7)\n    at MessageStore.module.exports.Publisher.trigger (/usr/share/nylas/resources/app.asar/src/flux/modules/reflux-coffee.js:218:30)\n    at /usr/share/nylas/resources/app.asar/src/flux/stores/message-store.js:344:26\n    at processImmediate [as _immediateCallback] (timers.js:383:17)\nFrom previous event:\n    at ModelQuery.then (/usr/share/nylas/resources/app.asar/src/flux/models/query.js:203:29)\n    at MessageStore._fetchFromCache (/usr/share/nylas/resources/app.asar/src/flux/stores/message-store.js:327:20)\n    at MessageStore._onApplyFocusChange (/usr/share/nylas/resources/app.asar/src/flux/stores/message-store.js:235:19)\n    at MessageStore._onApplyFocusChange (/usr/share/nylas/resources/app.asar/src/flux/stores/message-store.js:3:61)\n    at /usr/share/nylas/resources/app.asar/src/flux/stores/message-store.js:218:24"}
```

##### Do you have any third-party plugins installed?

None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Unclear, but I'm only using Gmail, specifically google apps.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Presently, any conversation I click on gets stuck "loading"

**Comment by 1beb** [comment]
0.4.25 also affected.

**Comment by Narga** [comment]
Me too, +1

**Comment by 1beb** [comment]
Upgraded to 16.04 and everything seems to be working as expected.

**Comment by Narga** [comment]
I'm using the git version with latest commit from Arch Linux AUR

**Comment by 1beb** [comment]
I updated to 16.04 and it's not happening.

**Comment by jstejada** [comment]
possible duplicate #1280

**Comment by 1beb** [comment]
@jstejada I would lean away from calling this a dup. Although possibly related the behaviour is distinct. In the other issue the reporter specified that the body is empty but he can go back and forth. 

In my case, I could do nothing but hard restart Nylas. No amount of clicking would get the screen to change beyond what was shown in the above example. 

When it happened once, every subsequent opening of the program it would happen again making it unusable. The only thing that would repair it was a removal and reinstall.

**Comment by jstejada** [comment]
I see, thanks for the additional details @1beb

**Comment by vanhonit** [comment]
Hi all,
In Fedora I found the problem when N1 try to detect timezone. Here the link [https://github.com/nylas/N1/issues/1929#issuecomment-219665164](issue). I fixed that problem on my repo https://github.com/vanhonit/N1. Hope can help everyone.

**Comment by jstejada** [comment]
Hey @vanhonit thanks for catching that. Do you think you can submit a PR with your fix so we can include it in the main N1 repo. Thanks!

**Comment by vanhonit** [comment]
Hi @jstejada,
I have submitted my patch to N1 repo.

**Comment by jstejada** [comment]
this pr has been merged in so I'm closing this issue!
