### ISSUE TITLE
N1 Filters menu not displayed

### ISSUE THREAD

**Issue by nobeh** [nylas/N1#189]
Great work Nylas Team!

Although, the plugin is enabled, the left bar menu is not displayed as documented in N1-Filters module. Screen attached.

Platform: Ubuntu 15.04
Linux Kernel: 3.19.0-31-generic 

suggested labels: bug platform-linux

![n1-filters](https://cloud.githubusercontent.com/assets/1003027/10715298/f1104d88-7b11-11e5-9c88-eb0a6a40b8a9.png)

**Comment by coagmano** [comment]
Can confirm on OSX El Capitan using N1 Version 0.3.19-de7d1bb
![fullscreen_26_10_2015__9_32_am](https://cloud.githubusercontent.com/assets/292857/10718351/77030b3a-7bc4-11e5-99ca-4c3c2641b93a.jpg)

**Comment by RoccoZocko** [comment]
Same here on Windows 10, latest verion of N1.

**Comment by bryceosterhaus** [comment]
Same for me. OSX Yosemite 10.10.5

**Comment by nobeh** [comment]
Debugged a bit more this issue. The error log that I get is:

```
Failed to load package named 'N1-Filters'
Error: Cannot find module 'react'
  at Module._resolveFilename (module.js:334:15)
  at Function.exports.register.Module._resolveFilename (/usr/share/nylas/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/behrooz/.nylas/packages/N1-Filters/lib/filters.coffee:1:9)
  at Object.<anonymous> (/home/behrooz/.nylas/packages/N1-Filters/lib/filters.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/nylas/resources/app.asar/src/coffee-cache.js:74:19)
  at Module.load (/usr/share/nylas/resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/behrooz/.nylas/packages/N1-Filters/lib/main.coffee:5:11)
  at Object.<anonymous> (/home/behrooz/.nylas/packages/N1-Filters/lib/main.coffee:5:1)
  at Module._compile (module.js:428:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/nylas/resources/app.asar/src/coffee-cache.js:74:19)
  at Module.load (/usr/share/nylas/resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/nylas/resources/app.asar/src/package.js:690:27)
  at /usr/share/nylas/resources/app.asar/src/package.js:196:34
  at Package.module.exports.Package.measure (/usr/share/nylas/resources/app.asar/src/package.js:172:15)
  at Package.module.exports.Package.load (/usr/share/nylas/resources/app.asar/src/package.js:186:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/nylas/resources/app.asar/src/package-manager.js:464:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/nylas/resources/app.asar/src/package-manager.js:441:14)
  at Atom.module.exports.Atom.startRootWindow (/usr/share/nylas/resources/app.asar/src/atom.js:693:21)
  at Object.<anonymous> (/usr/share/nylas/resources/app.asar/src/window-bootstrap.js:18:8)
  at Object.<anonymous> (/usr/share/nylas/resources/app.asar/src/window-bootstrap.js:29:4)
  at Module._compile (module.js:428:26)
  at Object.loadFile [as .js] (/usr/share/nylas/resources/app.asar/src/6to5.js:138:21)
  at Module.load (/usr/share/nylas/resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at window.onload (file:///usr/share/nylas/resources/app.asar/static/index.js:75:25)

Cannot find module 'react' Error: Cannot find module 'react'
  at Module._resolveFilename (module.js:334:15)
  at Function.exports.register.Module._resolveFilename (/usr/share/nylas/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/behrooz/.nylas/packages/N1-Filters/lib/filters.coffee:1:9)
  at Object.<anonymous> (/home/behrooz/.nylas/packages/N1-Filters/lib/filters.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/nylas/resources/app.asar/src/coffee-cache.js:74:19)
  at Module.load (/usr/share/nylas/resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/behrooz/.nylas/packages/N1-Filters/lib/main.coffee:5:11)
  at Object.<anonymous> (/home/behrooz/.nylas/packages/N1-Filters/lib/main.coffee:5:1)
  at Module._compile (module.js:428:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/nylas/resources/app.asar/src/coffee-cache.js:74:19)
  at Module.load (/usr/share/nylas/resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/nylas/resources/app.asar/src/package.js:690:27)
  at /usr/share/nylas/resources/app.asar/src/package.js:196:34
  at Package.module.exports.Package.measure (/usr/share/nylas/resources/app.asar/src/package.js:172:15)
  at Package.module.exports.Package.load (/usr/share/nylas/resources/app.asar/src/package.js:186:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/nylas/resources/app.asar/src/package-manager.js:464:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/nylas/resources/app.asar/src/package-manager.js:441:14)
  at Atom.module.exports.Atom.startRootWindow (/usr/share/nylas/resources/app.asar/src/atom.js:693:21)
  at Object.<anonymous> (/usr/share/nylas/resources/app.asar/src/window-bootstrap.js:18:8)
  at Object.<anonymous> (/usr/share/nylas/resources/app.asar/src/window-bootstrap.js:29:4)
  at Module._compile (module.js:428:26)
  at Object.loadFile [as .js] (/usr/share/nylas/resources/app.asar/src/6to5.js:138:21)
  at Module.load (/usr/share/nylas/resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at window.onload (file:///usr/share/nylas/resources/app.asar/static/index.js:75:25)
```
Then I tried to install `react` module:

```bash
$ (sudo) npm install react
```

which says:

```
react@0.14.2 node_modules/react
├── fbjs@0.3.2 (whatwg-fetch@0.9.0, ua-parser-js@0.7.9, core-js@1.2.6, loose-envify@1.1.0, promise@7.0.4)
└── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
```

I am not an expert on react or other Node modules. What am I missing here?

**Comment by coagmano** [comment]
I managed to fix the `cannot find module 'react'` error by changing `filters.coffee` and `filters.cjsx`.
Remove the line:
````coffee
    React = require 'react'
````
and Edit the line
````coffee
    {CategoryStore, Actions, Utils} = require 'nylas-exports'
````
to
````coffee
    {React, CategoryStore, Actions, Utils} = require 'nylas-exports'
````
Now it's giving an error `Cannot read property 'listen' of undefined` which traces back to a line in `filters-store.coffee`:
````coffee
    @listenTo Actions.deleteFilter, @_onDeleteFilter
````
Which goes beyond my knowledge of coffeescript and react.

**Comment by aayler** [comment]
Seeing same error on OSX 10.10.5, Nylas Version 0.3.23-94e0cb9 (0.3.23-94e0cb9).

Thanks!

**Comment by Lyndonneu** [comment]
same ....
pls solve this~

**Comment by jstejada** [comment]
hey guys, so the current filters package is a bit outdated, we're actually revamping the filters package and it will be available to play with very soon. sorry for the trouble!

**Comment by aayler** [comment]
Thanks for the update ... moving forward!

**Comment by nobeh** [comment]
Thanks for the update @jstejada 

This morning I downloaded the new 0.3.23 version and still the same. Just FYI.

**Comment by geekpete** [comment]
Same for me on OSX.

This plugin is kinda pivotal for my adoption of N1 over Thunderbird.

**Comment by ra100** [comment]
same as @coagmano `Cannot read property 'listen' of undefined`, I tried it also on 0.3.27, still doesn't work

**Comment by andreguilhon** [comment]
Same here. Any updates on this?! Maybe a guess of when it'll be corrected?

**Comment by nemesis** [comment]
Same here. Any updates? 

N1 Version 0.3.32-b11131d (0.3.32-b11131d)
OSX Version 10.11.2 (15C50)

**Comment by mbilker** [comment]
Hey, this plugin is being integrated into N1's core, not as a separate plugin. I am closing this issue.

**Comment by nobeh** [comment]
@mbilker Thanks for the follow-up. Could you please share the reference issue for the merge into core?

**Comment by mbilker** [comment]
It is not exactly a reference issue, but a reference commit. Support is coming with 0.3.33 or 0.3.34. The commit id is 606909e256c29e1157ba36392d3fa42032079fd1.

**Comment by nobeh** [comment]
Awesome! Can't wait to use it.
