### ISSUE TITLE
Cannot locate electron. Be sure you have run script/bootstrap first from /usr/bin

### ISSUE THREAD

**Issue by CaioAlonso** [nylas/N1#2]
I have installed N1 from nylas-0.3.14-amd64-282229e.deb on a Debian 8.2 system.
```
$ nylas             
Cannot locate electron. Be sure you have run script/bootstrap first from /usr/bin
```
However, I cannot find script/bootstrap anywhere on /usr/bin.

What am I missing?

**Comment by niedzielski** [comment]
Same issue. I tried to install it myself but couldn't quite get it together:

```
$ npm install -g electron-prebuilt@0.29.2
$ ELECTRON_PATH=/home/stephen/.node/bin nylas

Error opening app
The app provided is not a valid electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/master/docs

Error: Cannot find module '/usr/bin'
```

**Comment by mjanda** [comment]
Same issue on Kubuntu 15.04

**Comment by bengotow** [comment]
Hi folks, sorry for the hassle—I'm looking into this now. I believe the script/bootstrap that is being referenced is actually in the repo (https://github.com/nylas/N1/blob/master/script/bootstrap). Try `cd`ing into the N1 directory, running `./script/bootstrap` and then running the app via `./N1.sh --dev`. 

Hope that helps! We may just need to edit that error message.

**Comment by spang** [comment]
Hey there folks, this is a bit confusing. If you're launching from the command line, you need to run `/usr/share/nylas/nylas` and not `/usr/bin/nylas`. We're working on a fix for this!

**Comment by niedzielski** [comment]
@bengotow, @spang, desktop / menu shortcut and /usr/share/nylas/nylas work!

I tried building from source earlier but was having some issues I've not had time to look into yet. I think my version of Node.js is incompatible with script/bootstrap:

```
Node: v4.1.0
npm: v1.4.28

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ /home/stephen/opt/N1/build/node_modules/.bin/npm --userconfig=/home/stephen/opt/N1/.npmrc install --loglevel error --cwd=/home/stephen/opt/N1/build --ignoreStdout=true 



---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ /home/stephen/opt/N1/build/node_modules/.bin/npm --userconfig=/home/stephen/opt/N1/.npmrc install --loglevel error --cwd=/home/stephen/opt/N1/apm --ignoreStdout=true 

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp: /home/stephen/.node-gyp/4.1.0/common.gypi not found (cwd: /home/stephen/opt/N1/apm/node_modules/atom-package-manager/node_modules/keytar) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/stephen/opt/N1/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "/home/stephen/opt/node-v4.1.0-linux-x64/bin/node" "/home/stephen/opt/N1/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/stephen/opt/N1/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp: /home/stephen/.node-gyp/4.1.0/common.gypi not found (cwd: /home/stephen/opt/N1/apm/node_modules/atom-package-manager/node_modules/first-mate/node_modules/oniguruma) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/stephen/opt/N1/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "/home/stephen/opt/node-v4.1.0-linux-x64/bin/node" "/home/stephen/opt/N1/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/stephen/opt/N1/apm/node_modules/atom-package-manager/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp: /home/stephen/.node-gyp/4.1.0/common.gypi not found (cwd: /home/stephen/opt/N1/apm/node_modules/atom-package-manager/node_modules/git-utils) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/stephen/opt/N1/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "/home/stephen/opt/node-v4.1.0-linux-x64/bin/node" "/home/stephen/opt/N1/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/stephen/opt/N1/apm/node_modules/atom-package-manager/node_modules/git-utils
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! keytar@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@2.1.0 install script.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/home/stephen/opt/node-v4.1.0-linux-x64/bin/node" "/home/stephen/opt/N1/build/node_modules/.bin/npm" "--userconfig=/home/stephen/opt/N1/.npmrc" "install" "--loglevel" "error"
npm ERR! cwd /home/stephen/opt/N1/apm
npm ERR! node -v v4.1.0
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by spang** [comment]
@niedzielski great!!

Yeah, I believe you need node v0.10.38 for this to work—that's a side effect of the version of electron we're currently built on.

**Comment by ForumLiker** [comment]
I installed Electron, but anyway error "Cannot locate electron."
