### ISSUE TITLE
Bug: n1-unsubscribe doesn't work on 0.4.32

### ISSUE THREAD

**Issue by runofthemill** [nylas/N1#2113]
##### Are there any related issues?

Potentially #2106 

##### What operating system are you using?
OSX 10.11.4
##### What version of N1 are you using?
0.4.32-1de17e7
--

**Bug?**
After updating last night from 0.4.25 to 0.4.32, n1-unsubscribe doesn't show action button on either the list view or the message view. At first I thought maybe it was a problem with the less-is-more theme, which I also installed last night, but I switched to the default theme and the problem still exists. I looked in the developer console, and there are a number of issues (ignore the github-issues one; I was hacking a copy of that plugin) which I've appended to the end of this post.

##### Do you have any third-party plugins installed?
n1-unsubscribe
less-is-more theme
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

n/a

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

--

***Developer Console after reload***

```
Streaming log data to /var/folders/yj/201hb9l96zb8dw37n42n17bm0000gn/T/Nylas-N1-92500.92530.log
Window load time: 364ms
Failed to load package named 'n1-unsubscribe'
Error: Invalid package /Applications/Nylas N1.app/Contents/Resources/atom.asar
    at invalidArchiveError (ELECTRON_ASAR.js:137)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:430)
    at compileFileAtPath (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:78)
    at Object.defineProperty.value [as .js] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:203)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/thread-unsubscribe-store.es6:9)
    at Module._compile (module.js:413)
    at Object.defineProperty.value [as .es6] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/thread-unsubscribe-store-manager.es6:1)
    at Module._compile (module.js:413)
    at Object.defineProperty.value [as .es6] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Object.<anonymous> (quick_action.cjsx:1)
    at Object.<anonymous> (quick_action.cjsx:1)
    at Module._compile (module.js:413)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Object.<anonymous> (main.cjsx:1)
    at Object.<anonymous> (main.cjsx:1)
    at Module._compile (module.js:413)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Package.module.exports.Package.requireMainModule (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:543)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:198
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:176)
    at Package.module.exports.Package.load (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:190)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:513)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:490)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:710)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:735
Invalid package /Applications/Nylas N1.app/Contents/Resources/atom.asar Error: Invalid package /Applications/Nylas N1.app/Contents/Resources/atom.asar(…)
Warning: React.__spread is deprecated and should not be used. Use Object.assign directly or another helper function with similar semantics. You may be seeing this warning due to your compiler. See https://fb.me/react-spread-deprecation for more details.
ComponentRegistry.register(): A different component was already registered with the name ViewOnGithubButton
Error: ComponentRegistry.register(): A different component was already registered with the name ViewOnGithubButton
    at ComponentRegistry.register (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/component-registry.js:65)
    at ComponentRegistry.register (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/component-registry.js:3)
    at Object.activate (main.jsx [sm]:32)
    at Package.module.exports.Package.activateNow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:270)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:256
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:176)
    at Package.module.exports.Package.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:253)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:611)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:589
    at Config.module.exports.Config.transact (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/config.js:195)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:578)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:561)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:717)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:735
Failed to activate package named 'github-latest' Error: ComponentRegistry.register(): A different component was already registered with the name ViewOnGithubButton
    at ComponentRegistry.register (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/component-registry.js:65:15)
    at ComponentRegistry.register (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/component-registry.js:3:61)
    at Object.activate (/Users/jeremymiller/.nylas/dev/packages/github-latest/lib/main.jsx:50:21)
    at Package.module.exports.Package.activateNow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:270:27)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:256:26
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:176:15)
    at Package.module.exports.Package.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:253:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:611:21)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:589:29
    at Config.module.exports.Config.transact (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/config.js:195:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:578:23)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:561:46)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:717:23)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:735:25
Invalid package /Applications/Nylas N1.app/Contents/Resources/atom.asar
Error: Invalid package /Applications/Nylas N1.app/Contents/Resources/atom.asar
    at invalidArchiveError (ELECTRON_ASAR.js:137)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:430)
    at compileFileAtPath (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:78)
    at Object.defineProperty.value [as .js] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:203)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/thread-unsubscribe-store.es6:9)
    at Module._compile (module.js:413)
    at Object.defineProperty.value [as .es6] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/thread-unsubscribe-store-manager.es6:1)
    at Module._compile (module.js:413)
    at Object.defineProperty.value [as .es6] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Object.<anonymous> (quick_action.cjsx:1)
    at Object.<anonymous> (quick_action.cjsx:1)
    at Module._compile (module.js:413)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Object.<anonymous> (main.cjsx:1)
    at Object.<anonymous> (main.cjsx:1)
    at Module._compile (module.js:413)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204)
    at Module.load (module.js:357)
    at Function.Module._load (module.js:314)
    at Module.require (module.js:367)
    at require (internal/module.js:16)
    at Package.module.exports.Package.requireMainModule (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:543)
    at Package.module.exports.Package.activateConfig (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:287)
    at Package.module.exports.Package.activateNow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:266)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:256
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:176)
    at Package.module.exports.Package.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:253)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:611)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:589
    at Config.module.exports.Config.transact (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/config.js:195)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:578)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:561)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:717)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:735
Failed to activate package named 'n1-unsubscribe' Error: Invalid package /Applications/Nylas N1.app/Contents/Resources/atom.asar
    at invalidArchiveError (ELECTRON_ASAR.js:137:13)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:430:9)
    at compileFileAtPath (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:78:23)
    at Object.defineProperty.value [as .js] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:203:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/thread-unsubscribe-store.es6:9:15)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .es6] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/thread-unsubscribe-store-manager.es6:1:30)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .es6] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/ui/quick_action.cjsx:2:33)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/ui/quick_action.cjsx:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/main.cjsx:2:32)
    at Object.<anonymous> (/Users/jeremymiller/.nylas/packages/n1-unsubscribe/lib/main.cjsx:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Package.module.exports.Package.requireMainModule (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:543:27)
    at Package.module.exports.Package.activateConfig (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:287:12)
    at Package.module.exports.Package.activateNow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:266:14)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:256:26
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:176:15)
    at Package.module.exports.Package.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:253:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:611:21)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:589:29
    at Config.module.exports.Config.transact (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/config.js:195:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:578:23)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:561:46)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:717:23)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:735:25
 SCAN TABLE Category for SELECT `Category`.`data` FROM `Category`   
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ListTabularItem`. See https://fb.me/react-warning-keys for more information.
(node) warning: possible EventEmitter memory leak detected. 51 trigger listeners added. Use emitter.setMaxListeners() to increase limit.
console.trace()
```

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. We'll work with the `n1-unsubscribe` folks today and see if we can get this fixed.

**Comment by bengotow** [comment]
This should be fixed by a combination of https://github.com/colinking/n1-unsubscribe/pull/20 and e8af794adf826217865a7afa163c441a5003bc01, which we probably shouldn't have removed and will restore in a patch release.

**Comment by runofthemill** [comment]
looks to be all set - thanks for the quick fix!
