### ISSUE TITLE
Still cannot see emails in preview window

### ISSUE THREAD

**Issue by tropicalpriest** [nylas/N1#2143]
Getting this now. 
/usr/share/nylas/resources/app.asar/node_modules/react/node_modules/fbjs/lib/warning.js:44 Warning: React.__spread is deprecated and should not be used. Use Object.assign directly or another helper function with similar semantics. You may be seeing this warning due to your compiler. See https://fb.me/react-spread-deprecation for more details.warning @ /usr/share/nylas/resources/app.asar/node_modules/react/node_modules/fbjs/lib/warning.js:44
/usr/share/nylas/resources/app.asar/src/flux/stores/database-store.js:381 SCAN TABLE Category for SELECT Category.data FROM Category

/usr/share/nylas/resources/app.asar/src/nylas-env.js:309 TypeError: Cannot read property 'format' of undefined
at Object.module.exports.Utils.fullTimeString (/usr/share/nylas/resources/app.asar/src/flux/models/utils.js:109:45)
at MessageTimestamp.render (/usr/share/nylas/resources/app.asar/internal_packages/message-list/lib/message-timestamp.js:45:24)
at MessageTimestamp.render (/usr/share/nylas/resources/app.asar/internal_packages/message-list/lib/message-timestamp.js:3:61)
at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:687:34)
at ReactCompositeComponentMixin._renderValidatedComponent

**Comment by jackiehluo** [comment]
Going to close this issue for now—this issue should be fixed!
