### ISSUE TITLE
Bug: "Error: An extension applied a tranform to the draft that it could not reverse."

### ISSUE THREAD

**Issue by runofthemill** [nylas/N1#2188]
##### Are there any related issues?
Not that I could find with the same error

##### What operating system are you using?
OSX 10.11.4
##### What version of N1 are you using?
0.4.33-e8f137e

--

**Bug?**
After replying to a thread, the error popped up in the dev console. Reply got sent & received fine, so non-critical (as far as I can tell).

```
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:309 Error: An extension applied a tranform to the draft that it could not reverse.
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/draft-store.js:576:44
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)module.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:309
```

##### Do you have any third-party plugins installed?
less-is-more-master (theme)
n1-unsubscribe

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Unknown

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I forwarded the same thread to myself to test - got the same error when both the body message was identical and when the body message only included 1 line of text.

**Comment by enoversum** [comment]
@runofthemill I have something similar, but hesitated to report in. I use the Windows version, both at work and at home. When creating replies with emoticons (the ones that ship with N1, like), I get a similar message. Could that be the case for you as well?
I hesitated as I only get the error messages at work, but not on my home machine, so I assumed some kind of hickup with an extension. Even getting rid of all extensions though didn't help.

**Comment by jstejada** [comment]
Hmm it's interesting that you are getting the error even with all third party extensions uninstalled. What set of built-in extensions do you have enabled? Can you tell me the exact actions you took to reproduce the error? Thanks!

**Comment by enoversum** [comment]
@jstejada Yes, I open a conversation, reply to it, using the built-in emoticon function and send+archive it with Strg+Enter. No more than that. Throws an error at work, but not at home. New mail in a new window is fine though.

**Comment by jackiehluo** [comment]
Oh, you know what? I think that might be a problem with the emoji picker... The regex for that might not be able to convert an emoji character back to an image. We were waiting on updates to the `emoji-data` module.

**Comment by enoversum** [comment]
@jackiehluo How come this only happens on one computer and not the other then? Also, I can see the image itself when creating the e-mail.

**Comment by jackiehluo** [comment]
Yeah, that part doesn't make much sense. Are you using the same emoji on both computers? And you should see the image when creating the email! It only converts back to the character when you send.

**Comment by enoversum** [comment]
Yes, yes, I am using the wink emoticon a lot, on both computers, just tried it. And I just realised, by using another e-mail client, that these emoticons show up as unknown characters. Since emojis are baked into Android, I can see them on my smartphone without a glitch.

**Comment by jackiehluo** [comment]
Strange... We'll keep an eye on that. Hopefully it gets fixed when we have a complete regex for the emoji.

And yeah, that's the reason we use images within N1. Not all of the characters render properly in Electron. We send them as characters (not images) so that they work as expected in other places.

**Comment by enoversum** [comment]
Okay, good to know, even though that means that correspondents on desktop computers possibly do not see them (so far?) :cry: .

**Comment by enoversum** [comment]
Hi there, @jackiehluo 

just to report back: Since the new version the error message still appears, like this:

`C:\Users\xxx\AppData\Local\nylas\app-0.4.38\resources\app.asar\src\nylas-env.js:305 Error: Extension EmojiComposerExtension applied a tranform to the draft that it could not reverse.
    at C:\Users\xxx\AppData\Local\nylas\app-0.4.38\resources\app.asar\src\flux\stores\draft-store.js:582:44
    at tryCatcher (C:\Users\xxx\AppData\Local\nylas\app-0.4.38\resources\app.asar\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\xxx\AppData\Local\nylas\app-0.4.38\resources\app.asar\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\xxx\AppData\Local\nylas\app-0.4.38\resources\app.asar\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\xxx\AppData\Local\nylas\app-0.4.38\resources\app.asar\node_modules\bluebird\js\main\promise.js:245:10)
    at Async._drainQueue (C:\Users\xxx\AppData\Local\nylas\app-0.4.38\resources\app.asar\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\xxx\AppData\Local\nylas\app-0.4.38\resources\app.asar\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\xxx\AppData\Local\nylas\app-0.4.38\resources\app.asar\node_modules\bluebird\js\main\async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)`

So, it seems there is still something going wrong :cry: .

**Comment by jcuenod** [comment]
I'm having this issue but it looks like nothing's happened here for a couple of months. Is there any update on this?

**Comment by bengotow** [comment]
The original issue has been resolved — we actually removed this code in a recent release!
