### ISSUE TITLE
TypeError: combination.replace is not a function

### ISSUE THREAD

**Issue by evanemolo** [nylas/N1#2255]
##### What operating system are you using?
OS X 10.11.4

##### What version of N1 are you using?
<strike>Version 0.4.38-27d21d1 (0.4.38-27d21d1)</strike>

version 0.4.33 and later. version 0.4.32 works fine.

--

**Bug?**

When loading N1, the following error is in the console, leaving N1 unusable because it hangs on the loading display:

```
Streaming log data to /var/folders/r9/f0fbmzcj4w74txdn_7d_mgj40000gn/T/Nylas-N1-70673.70677.log
TypeError: combination.replace is not a function
    at _bindSingle (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/mousetrap/mousetrap.js:826:39)
    at Mousetrap.self._bindMultiple (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/mousetrap/mousetrap.js:873:17)
    at Mousetrap.bind (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/mousetrap/mousetrap.js:900:28)
    at Function.bind (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/mousetrap/mousetrap.js:998:58)
    at KeymapManager.ensureKeystrokesRegistered (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/keymap-manager.js:167:25)
    at Object.keys.forEach.command (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/keymap-manager.js:67:25)
    at Array.forEach (native)
    at KeymapFile.load.e [as load] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/keymap-manager.js:61:28)
    at KeymapManager.loadKeymaps (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/keymap-manager.js:109:23)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:703:20)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startSecondaryWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:749:12)
    at Object.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/secondary-window-bootstrap.js:20:12)
    at Object.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/secondary-window-bootstrap.js:31:4)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at setupWindow (file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js:70:3)
    at window.onload (file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js:109:5)

```

##### Do you have any third-party plugins installed?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

**Comment by evanemolo** [comment]
In case anyone else experiences this issue, the fix is to `rm -rf`the ~/.nylas dir and start from scratch.
