### ISSUE TITLE
Office 365 folder created but not displayed

### ISSUE THREAD

**Issue by pfista** [nylas/N1#2425]
##### Are there any related issues?
#2273

##### What operating system are you using?
10.11.6 Beta (15G7a)

##### What version of N1 are you using?
Version 0.4.40-85cf726 (0.4.40-85cf726)

**Bug?**
##### Do you have any third-party plugins installed?
![image](https://cloud.githubusercontent.com/assets/728526/16019788/b70e8564-315f-11e6-86dd-e35f9bdb1b2b.png)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Office 365

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. When adding through the folder sidebar
2. When creating a new folder through move to folder in an email

```
40012:08:42  RunCopycurl -X POST -d '{"display_name":"Archive"}' "https://...:@api.nylas.com/folders"
20012:06:02  RunCopycurl -X GET -H "Accept: message/rfc822" "https://...:@api.nylas.com/messages/..."
20012:02:04  RunCopycurl -X GET -H "Accept: message/rfc822" "https://...:@api.nylas.com/messages/..."
40012:01:44  RunCopycurl -X POST -d '{"display_name":"Archive"}' "https://...:@api.nylas.com/folders"
20012:00:59  RunCopycurl -X GET "https://...:@api.nylas.com/account"
20012:00:59  RunCopycurl -X GET "https://...:@api.nylas.com/account"
20012:00:59  RunCopycurl -X GET "https://...:@api.nylas.com/account"
20012:00:58  RunCopycurl -X GET "https://...:@api.nylas.com/contacts/rankings"
20012:00:58  RunCopycurl -X GET "https://...:@api.nylas.com/contacts/rankings"
```
```
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:306 APIError: folder with name "Archive" already exists
    (No stack trace)
From previous event:
    at NylasAPIRequest.run (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/nylas-api.js:132:14)
    at NylasAPI.makeRequest (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/nylas-api.js:293:18)
    at SyncbackCategoryTask.performRemote (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/tasks/syncback-category-task.js:77:31)
    at SyncbackCategoryTask.runRemote (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/tasks/task.js:275:19)
    at TaskQueue._processTask (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/task-queue.js:295:19)
    at TaskQueue._processTask (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/task-queue.js:3:61)
    at TaskQueue._processQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/task-queue.js:279:14)
    at TaskQueue._processQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/task-queue.js:3:61)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/task-queue.js:444:21
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/underscore/underscore.js:768:19
```

It says the folder already exists, but it isn't displayed in sidebar, or when trying to move messages to a folder.

![image](https://cloud.githubusercontent.com/assets/728526/16019964/9f67b434-3160-11e6-9d87-0d2a9f93c93c.png)

**Comment by pfista** [comment]
The archive folder is showing up now, I guess it took some time to sync.

![image](https://cloud.githubusercontent.com/assets/728526/16020117/4503df6c-3161-11e6-8f9f-dc3a7fe71732.png)
