### ISSUE TITLE
Exception when Ensuring setuptools and pip versions on Ubuntu 16.04

### ISSUE THREAD

**Issue by tenleftfingers** [nylas/N1#2532]
I was tracking a similar issue but it seems to have been deleted/I can't find it. When I run sudo -H ./setup.py I get an error:

Ensuring libsodium version...
Ensuring redis version...
redis-2.8.17 installed.
Ensuring setuptools and pip versions...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

##### What operating system are you using?
Ubuntu 16.04 64-bit

##### What version of N1 are you using?
Master

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

**Feature Request?**

**Comment by bengotow** [comment]
Hey! N1 is written in Javascript - you might need to post this over on the sync-engine repo? github.com/nylas/sync-engine
