### ISSUE TITLE
Issue building nylas on windows

### ISSUE THREAD

**Issue by JimmyHodgson** [nylas/N1#2588]
I can't build on windows 10 64bit I get the following output when running script\bootstrap. Anyone know how to fix this?

D:\Docs\code\N1>script\bootstrap
Node: v5.10.1
npm: v3.8.3
Python: v2.7.12

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="D:\Docs\code\N1\.npmrc" install --loglevel error --cwd="D:\\Docs\\code\\N1\\build" --ignoreStdout=true

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Docs\code\N1\build\node_modules\minidump
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=D:\\Docs\\code\\N1\\.npmrc" "install" "--loglevel" "error"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minidump@0.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minidump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Docs\code\N1\build\npm-debug.log

**Comment by emorikawa** [comment]
See if you can build `minidump` by itself. We use VS Studio 2013. I've had historic issues with 2015 and some node modules.

**Comment by JimmyHodgson** [comment]
I wasn't able to build minidump either, I have visual studio community 2015 and had to install sdk for 8.1 after that that error was resolved however i am running into another issue involving c++ developer tools which I forgot to install while installing vs 2015.

**Comment by bengotow** [comment]
Sounds good - I'm not sure why VS 2013 is required (as opposed to VS 2015), but we've heard from the Atom team that work would be required to support VS 2015 in the build process. If it doesn't work after you install the C++ tools for VS 2015, you may need to downgrade, or we can see if we can make changes to support the new version!

**Comment by bengotow** [comment]
Actually, Atom's instructions allow you to use VS 2015 now—we should probably investigate what they changed to make 2015 work: https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md

**Comment by JimmyHodgson** [comment]
I installed the c++ tools for vs 2015 but after running scripts\clean and scripts\bootstrap again minidump won't build again, now I'm getting an error saying v120 o cpp tools are needed, seems I might have to downgrade to vs 2013 and try again.

**Comment by aggieben** [comment]
I have the same issue.  The change happened (as I understand it) down in node-gyp, where they didn't have support for 2015 at one time, and now they do.

**Comment by adamporter** [comment]
Win10 x64 here.

My thoughts are that this is entirely a VS issue. No matter what permutation of node, python, or path variables I tried, msbuild and node-gyp errors were all I got.

I had 2015 Enterprise installed. Looking back, I never had all the C++ tools installed. I went back in and added those components, but no luck. I uninstalled and reinstalled everything else (even switching versions and 32 vs. 64 bit)...still no love. Even looking at the Atom instructions that @bengotow pointed out, above, didn't help.

It wasn't until I installed VS2013 Pro with Update 5 that I got things to work. I installed it, changed the gyp PATH variables I had (to 2013 from 2015), and reran 'script\bootstrap'. That was literally all it took.

Ultimately, I believe that either:
1. VS2015 still doesn't work reliably for N1 (for whatever reason)
**or**
2. VS2015 **must** be installed with the C++ components from the initial install, in order for the N1 build to work.

I don't have the time or patience to test theory #2, but that's my current thought.

**Comment by harish-myaccount** [comment]
I could solve this minidump error with 
**npm config set msvs_version 2015 --global**

After that I ran into this error

\N1\build\node_modules\.bin\npm"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bengotow** [comment]
Hey folks! I've been working on N1 from Windows 10 for the last few days, and wanted to share a configuration that works:
- NodeJS 4.2+
- Visual Studio 2013 Community Edition
   If you have multiple versions installed, use `npm config set msvs_version 2015 --global` to select it.

Before running `script/bootstrap`, be sure to run `git clean -xdf`. If you've previously had problems building N1, you may have partially built or incorrectly built node modules in your working copy. `npm` doesn't always realize that it needs to rebuild them, which can lead to super strange issues. 

Sorry that getting N1 to build on Windows is such a pain. We depend on a handful of native node modules, so we're somewhat constrained by their individual build requirements.

**Comment by pwasiewicz** [comment]
I'm afraid that Visual Studio 2013 Community Edition is not available for download nowadays (it is available only for MSDN subscribers). Any chance to get build work with VS 2015?

**Comment by youngtraktor** [comment]
I would like to know how to build N1 with Visual Studio 2015 now that 2013 can't be downloaded.

Also, eventually I managed to fix my minidump issue, but I ran into this instead shortly after:
```
npm ERR! better-sqlite3@1.3.6 install: `node install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@1.3.6 install script 'node install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the better-sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs better-sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls better-sqlite3
npm ERR! There is likely additional logging output above.
```
