### ISSUE TITLE
script/bootstrap build failed

### ISSUE THREAD

**Issue by xdutaotao** [nylas/N1#2620]
##### What operating system are you using?
Ubuntu 14.04  3.13.0-39-generic #66-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

When I try to build my env, i get below errors. Anyone can give me some suggestion?  gyp_main.py no --no-parallel options ?  Anything wrong to my build env ?

##### build error:
===>>N1-0.4.45 [master] script/bootstrap

Node: v6.3.0
npm: v3.3.10

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/home/lt/code/N1/N1-0.4.45/.npmrc" install --loglevel error --cwd="/home/lt/code/N1/N1-0.4.45/build" --ignoreStdout=true 

(node:23347) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Running "add-nylas-build-resources" task
No extra Nylas resources added

Done, without errors.

---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ "/home/lt/code/N1/N1-0.4.45/build/node_modules/.bin/npm" --userconfig="/home/lt/code/N1/N1-0.4.45/.npmrc" --target=0.10.40 install --loglevel error --cwd="/home/lt/code/N1/N1-0.4.45/apm" --ignoreStdout=true 

(node:23354) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/lt/code/N1/N1-0.4.45/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-39-generic
gyp ERR! command "/home/lt/.nvm/versions/node/v6.3.0/bin/node" "/home/lt/code/N1/N1-0.4.45/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lt/code/N1/N1-0.4.45/apm/node_modules/keytar
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-39-generic
npm ERR! argv "/home/lt/.nvm/versions/node/v6.3.0/bin/node" "/home/lt/code/N1/N1-0.4.45/build/node_modules/.bin/npm" "--userconfig=/home/lt/code/N1/N1-0.4.45/.npmrc" "--target=0.10.40" "install" "--loglevel" "error"
npm ERR! node v6.3.0
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by bengotow** [comment]
Node 6 and npm 3 should be fine—can you try going to `./node_modules/keytar` and running `node-gyp rebuild`? You may be missing GCC or another C++ build tool.

**Comment by bengotow** [comment]
Closing due to inactivity - hope you got it worked out!

**Comment by geert95** [comment]
running in to the same problemens as @xdutaotao , even the rebuild wouldn't give any success. Any thoughts how to get it running @bengotow ?

`npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild`

**Comment by harish-myaccount** [comment]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\HobbyProjects\N1-0.4.52\build\node_modules\npm\node_modules\node-gyp\lib\b                                                                                           uild.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\HobbyProjects\\N1-0.4.52\\build\\node_modules\\npm\\node_mod                                                                                           ules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\HobbyProjects\N1-0.4.52\apm\node_modules\keytar
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\HobbyProjects\\N1-0.4.52\\build\\node_modules\\npm\\bin\\npm-cl                                                                                           i.js" "--userconfig=D:\\HobbyProjects\\N1-0.4.52\\.npmrc" "--target=0.10.40" "install" "--loglevel" "error"
npm ERR! node v6.6.0
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.

**Comment by harish-myaccount** [comment]
However global install doesn't throw this error

D:\HobbyProjects\N1-0.4.52>npm install keytar -g

> keytar@3.0.2 install C:\Users\DELL\AppData\Roaming\npm\node_modules\keytar
> node-gyp rebuild


C:\Users\DELL\AppData\Roaming\npm\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Users\DELL\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  keytar_win.cc
  win_delay_load_hook.cc
c:\users\dell\appdata\roaming\npm\node_modules\keytar\node_modules\nan\nan_maybe_43_inl.h(220): warning C4996: 'v8::Array::CloneElementAt': was declared deprecated (compiling source file ..\src\main.cc) [C:\Use
rs\DELL\AppData\Roaming\npm\node_modules\keytar\build\keytar.vcxproj]
  c:\users\dell\.node-gyp\6.6.0\include\node\v8.h(3033): note: see declaration of 'v8::Array::CloneElementAt' (compiling source file ..\src\main.cc)
c:\users\dell\appdata\roaming\npm\node_modules\keytar\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanObject::New': was declared deprecated (compiling source file ..\src\main.cc) [C
:\Users\DELL\AppData\Roaming\npm\node_modules\keytar\build\keytar.vcxproj]
  c:\users\dell\.node-gyp\6.6.0\include\node\v8.h(4007): note: see declaration of 'v8::BooleanObject::New' (compiling source file ..\src\main.cc)
C:\Users\DELL\AppData\Roaming\npm\node_modules\keytar\node_modules\nan\nan.h(2017): warning C4996: 'v8::Object::SetAccessor': was declared deprecated (compiling source file ..\src\main.cc) [C:\Users\DELL\AppDat
a\Roaming\npm\node_modules\keytar\build\keytar.vcxproj]
  c:\users\dell\.node-gyp\6.6.0\include\node\v8.h(2756): note: see declaration of 'v8::Object::SetAccessor' (compiling source file ..\src\main.cc)
     Creating library C:\Users\DELL\AppData\Roaming\npm\node_modules\keytar\build\Release\keytar.lib and object C:\Users\DELL\AppData\Roaming\npm\node_modules\keytar\build\Release\keytar.exp
  Generating code
  Finished generating code
  keytar.vcxproj -> C:\Users\DELL\AppData\Roaming\npm\node_modules\keytar\build\Release\\keytar.node
  keytar.vcxproj -> C:\Users\DELL\AppData\Roaming\npm\node_modules\keytar\build\Release\keytar.pdb (Full PDB)
C:\Users\DELL\AppData\Roaming\npm
`-- keytar@3.0.2
  `-- nan@2.3.2

**Comment by h4ckm03d** [comment]
@xdutaotao I've encounter same problem here. but from keytar issue. https://github.com/atom/node-keytar/issues/6

need some package to build

`sudo apt-get install g++ libgnome-keyring-dev`

or

`sudo dnf install gcc-c++ libgnome-keyring-devel`

after install 2 package above. `npm install` run smoothly.
