### ISSUE TITLE
TypeError: this.notifyFailure is not a function

### ISSUE THREAD

**Issue by cdalbergue** [nylas/N1#2795]
##### Are there any related issues?

None

##### What operating system are you using?
Arch

##### What version of N1 are you using?
0.4.47

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No, clean install, deleted .nylas folder

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Can't start N1

After running script/bootstrap, I am notified that everything worked fine. But when I launch N1, this is the error I am getting : 
```
# clement @ krotnein in ~/Downloads/N1-0.4.47 [14:43:02] 
$ ./N1.sh --test

[26066:0902/144334:ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
TypeError: this.notifyFailure is not a function
    at ConfigPersistenceManager.observe (config-persistence-manager.es6:91:12)
    at new ConfigPersistenceManager (config-persistence-manager.es6:20:10)
    at Application.start (application.es6:43:37)
    at EventEmitter.app.on (/home/clement/Downloads/N1-0.4.47/src/browser/main.js:168:24)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by emorikawa** [comment]
@cdalbergue The "Running without the SUID sandbox" error is expected. See https://github.com/electron/electron/issues/1482

The `this.notifyFailure` is not a function error seems to be coming from a piece of code that watches the config file. Do you properly have `~/.nylas/config.json` setup properly?

**Comment by bengotow** [comment]
This bug was fixed in the latest release. Cheers!
