### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by iamchathu** [nylas/N1#28]
I would like to try N1 in Windows 8.1 (64-bit). I installed cloned the repo and installed the dependencies.How to build the repo for windows.
I tried running build.cmd i get an error

```
Node: v0.12.7
npm: v2.11.3
Python: v2.7.9
F:\GitHub\N1\script\bootstrap:44
    throw new Error("Building for win32 with architecture "+targetArch+". Are
          ^
Error: Building for win32 with architecture x64. Are you sure you meant to do th
is?
    at makeSqlite3Command (F:\GitHub\N1\script\bootstrap:44:11)
    at bootstrap (F:\GitHub\N1\script\bootstrap:72:31)
    at F:\GitHub\N1\script\bootstrap:192:3
    at F:\GitHub\N1\script\utils\verify-requirements.js:21:9
    at F:\GitHub\N1\script\utils\verify-requirements.js:115:5
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

```

**Comment by gardner** [comment]
Try with node version 0.10.28

**Comment by gardner** [comment]
Your's looks like a different problem but currently N1 is only building against node v0.10.x. Maybe give that a try?

**Comment by jsjan** [comment]
``Error: Building for win32 with architecture x64. Are you sure you meant to do th
is?``
should explain this. You said you run Win8.1 with 64-bit (which is x64), somebody should try this on a 32-bit Windows.

**Comment by iamchathu** [comment]
I'm using Win8.1 64bt.I installed dependancies and then ran build.cmd in scripts folder.

**Comment by slnj** [comment]
@iamchathu Thats not the point, I mean Win32 is the 32-bit API for Windows so it should work with a 32-bit Windows.

**Comment by bengotow** [comment]
Hi folks—I'm the author of that not-very-helpful error in script/bootstrap.

Earlier this year, there was only a 32-bit version of Electron for Windows. We put in that check to ensure that our CI server never got moved to a 64-bit box, since it would compile sqlite in 64-bit and we'd be loading it into a 32-bit version of NodeJS.

This is no longer the case — Electron became available for 64-bit Windows in April (https://github.com/atom/electron/issues/980). Would love to know if you're able to remove that warning and build the whole thing for 64-bit Windows.

**Comment by slnj** [comment]
So I removed the warning, but not I get an error when it tries to install node-gyp
```
---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ C:\Users\Jan\Documents\Test\N1\build\node_modules\.bin\npm --userconfig=C:\Users\Jan\Documents\Test\N1\.npmrc install --loglevel error --cwd=C:\Users\Jan\Documents\Test\N1\apm --ignoreStdout=true

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Jan\Documents\Test\N1\build\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Jan\\Documents\\Test\\N1\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jan\Documents\Test\N1\apm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\oniguruma
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Jan\Documents\Test\N1\build\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Jan\\Documents\\Test\\N1\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jan\Documents\Test\N1\apm\node_modules\atom-package-manager\node_modules\git-utils
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! oniguruma@4.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@4.2.4 install script.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.3.9600
npm ERR! command "node" "C:\\Users\\Jan\\Documents\\Test\\N1\\build\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\Jan\\Documents\\Test\\N1\\.npmrc" "install" "--loglevel" "error"
npm ERR! cwd C:\Users\Jan\Documents\Test\N1\apm
npm ERR! node -v v0.12.0
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```
I looked up this in the web uninstalled Visual C++ 2010 Redist installed Win7.1 SDK etc. but got this error, it says it fails on ``node-gyp rebuild``. Can anyone of you tell me how to fix this?

**Comment by iamchathu** [comment]
@bengotow I would like help to test this.How would i change script/bootstrap to support Win64

**Comment by slnj** [comment]
@iamchathu Try this one: https://github.com/slnj/N1, removed it in the last commit.

**Comment by iamchathu** [comment]
I think now it's a error in some configuration. Am i missed something?

```
Node: v0.12.7
npm: v2.11.3
Python: v2.7.9

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig=F:\GitHub\N1\.npmrc install --loglevel error --cwd=F:\G
tHub\N1\build --ignoreStdout=true



---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ F:\GitHub\N1\build\node_modules\.bin\npm --userconfig=F:\GitHub\N1\.npmr
 install --loglevel error --cwd=F:\GitHub\N1\apm --ignoreStdout=true

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.


---> Cleaning apm via `apm clean`


F:\GitHub\N1\apm\node_modules\atom-package-manager\lib\auth.js:14
      throw error;
            ^
Error: The specified procedure could not be found.

F:\GitHub\N1\apm\node_modules\atom-package-manager\node_modules\keytar\build\Re
ease\keytar.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (F:\GitHub\N1\apm\node_modules\atom-package-manager\n
de_modules\keytar\lib\keytar.js:4:12)
    at Object.<anonymous> (F:\GitHub\N1\apm\node_modules\atom-package-manager\n
de_modules\keytar\lib\keytar.js:58:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

```

**Comment by slnj** [comment]
```
F:\GitHub\N1\apm\node_modules\atom-package-manager\lib\auth.js:14
      throw error;
            ^
Error: The specified procedure could not be found.
```
Should be a problem of apm not of N1. I think its because you are using node 0.12, regarding to [this](https://github.com/atom-archive/electron-starter/issues/78) you'll need node 0.10 because of apm.
