### ISSUE TITLE
"A dynamic link library (DLL) initialization routine failed" whilst building on Windows 10

### ISSUE THREAD

**Issue by bitttttten** [nylas/N1#2819]
##### Are there any related issues?
Not that I can find

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.49

I am running `script/bootstrap` and getting the following error:

```
---> Cleaning apm via `apm clean`

D:\Applications\N1\apm\node_modules\atom-package-manager\lib\auth.js:14
      throw error;
            ^
Error: A dynamic link library (DLL) initialization routine failed.
D:\Applications\N1\apm\node_modules\keytar\build\Release\keytar.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Applications\N1\apm\node_modules\keytar\lib\keytar.js:4:12)
    at Object.<anonymous> (D:\Applications\N1\apm\node_modules\keytar\lib\keytar.js:58:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Segmentation fault

```

The full output of `script/bootstrap` can be found [here](http://pastebin.com/eWVCLU0K). Any idea of what is causing this? I have Visual Studio 2015 installed already. I had a previous issue with keytar, so I just cd'd into apm and ran `npm install keytar` and now I'm presented with this.

**Comment by emorikawa** [comment]
`keytar` has had serious compatibility issues with Visual Studio 2015. Visual Studio 2013 tends to more reliably builds it.

**Comment by bitttttten** [comment]
thanks for the tip evan! i've exported the `GYP_MSVS_VERSION` as per the docs (i'm running `export GYP_MSVS_VERSION=2013`) as it's still failing. any tips? is there a way to check whether node-gyp is picking up 2013?

i'm doing the following:

```
bitttttten MINGW64 ~/Applications/N1 (master)
$ export GYP_MSVS_VERSION=2013

bitttttten MINGW64 ~/Applications/N1 (master)
$ echo $GYP_MSVS_VERSION
2013

bitttttten MINGW64 ~/Applications/N1 (master)
$ script/bootstrap
```

**Comment by bitttttten** [comment]
I don't know what happened although I can go further now after attempting once again, although now I'm presented with this error:

```
npm WARN package.json nylas@0.4.54 No license field.
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://iojs.org/download/release/v1.4.0/iojs-v1.4.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (D:\AppData\Roaming\npm\node_modules\node-gyp\lib\install.js:220:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (D:\AppData\Roaming\npm\node_modules\node-gyp\node_modules\request\request.js:954:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:361:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Applications\N1\node_modules\keytar
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```


..it's rather large so the full output [I have uploaded to pastebin here](http://pastebin.com/3B9ZjBKg).

That [doesn't seem to be a version that's available](https://iojs.org/download/release/), however 1.4.1 does and I just thought I'd ~ try ~ and patch it in by forcing 1.4.1 to download although then I was presented with [this](http://pastebin.com/w6xeaEAY) so I thought I wouldn't go any further.

Thanks!

**Comment by bengotow** [comment]
Hey! It sounds like it's trying to interpret the Electron version as an io.js version, which is really strange. I've been working on Windows recently and made a few changes in 0888c5c that may help out. Our team uses Visual Studio 2013 and NodeJS 4.2 on Windows. 

If you previously had problems building, you may have half-built or incorrectly-built node modules inside the project directory that `apm` doesn't realize it needs to rebuild. You can reset your working copy with `git clean -xdf` so `script/bootstrap` runs from scratch. Can you try that and let me know if you still have trouble?

Sorry, Windows is definitely the hardest platform to build Node projects on...

**Comment by bitttttten** [comment]
Hi!

Many thanks for following this up. I understand about the Windows pain.. so I am keen to help although I really appreciate the tips.

I'm not building via VS2013, just the cli. I have 2013 installed and using Node6.

Yes I did try and rebuild after update so I followed your advice and cleaned it out. Right now I'm on 57fbc0b9a1da1b10f7e0fac057151ab4ee745190, so a few commits ahead, and I'm now getting this:

```
bitttttten@hello MINGW64 ~/Applications/N1 (master)
$ script/bootstrap
Node: v6.6.0
npm: v3.10.6
Python: v2.7.11

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="D:\Applications\N1\.npmrc" install --loglevel error --cwd="D:\\Applications\\N1\\build" --ignoreStdout=true

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Applications\N1\build\node_modules\runas
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=D:\\Applications\\N1\\.npmrc" "install" "--loglevel" "error"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
```

I've [dumped the end of my log file here](http://hastebin.com/litaqiyosu.log). If you don't have time for me/this then I completely understand. If you would like me to do anything else to help you debug/understand, that's fine with me.
