### ISSUE TITLE
Installing on Fedora 23 fails: Cannot find module '../build/Release/git.node'

### ISSUE THREAD

**Issue by galvao** [nylas/N1#2826]
After solving a few issues (had to install libgnome-keyring-devel), I'm stuck with this error message when running script/bootstrap.

See below for the whole installation process:

```bash
sudo ./script/bootstrap                                           
Node: v0.10.42
npm: v3.3.10

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/opt/N1/.npmrc" install --loglevel error --cwd="/opt/N1/build" --ignoreStdout=true 

Ignoring node_modules, which is missing.
Running "add-nylas-build-resources" task
No extra Nylas resources added

Done, without errors.


---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ "/opt/N1/build/node_modules/.bin/npm" --userconfig="/opt/N1/.npmrc" --target=0.10.40 install --loglevel error --cwd="/opt/N1/apm" --ignoreStdout=true 



---> Flattening apm package tree
     This runs `npm dedupe` on apm's `npm` dependency.
     We use this to prevent paths over 260 characters on Windows.

     $ "/opt/N1/build/node_modules/.bin/npm" --userconfig="/opt/N1/.npmrc" --target=0.10.40 dedupe --cwd="/opt/N1/apm/node_modules/npm" --ignoreStderr=true --ignoreStdout=true 



---> Cleaning apm via `apm clean`


module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/N1/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/opt/N1/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

How can I solve this?

**Comment by bengotow** [comment]
Hi there—can you try running this with Node 4 or above and see what happens? I don't know that the project supports 0.10.x anymore.

**Comment by galvao** [comment]
@bengotow Sorry, but I can't. This is the current version of Node supported by Fedora23 and quite frankly Node still seems too unstable for me to try installing v4 (See below, what happened when I've tried).
So, I guess if Node v4 is a requirement Fedora 23 is out of the picture.

---
This happened while trying to install Node 4:

```bash
sudo curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
[sudo] password for zaphod: 

## Installing the NodeSource Node.js v4.x LTS Argon repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "fc23-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_4.x/fc/23/x86_64/nodesource-release-fc23-1.noarch.rpm'

## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.qylYPqtHxu' 'https://rpm.nodesource.com/pub_4.x/fc/23/x86_64/nodesource-release-fc23-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.qylYPqtHxu'
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Inappropriate ioctl for device)
Error executing command, exiting
```

**Comment by MartinNowak** [comment]
Also happens with node v4.5.0.

**Comment by bengotow** [comment]
Ahh yeah sorry, I thought the readme mentioned keyring-devel but it might not! Cheers—

**Comment by galvao** [comment]
@MartinNowak Thank you very much for your answer. I've finally solved this by removing the entire N1 tree (simple rm -rf) and beginning the process all over again (since now I have libgnome-keyring-devel).
@bengotow You guys should really update your docs =)
