### ISSUE TITLE
0.4.201 (11/3/16) There is an issue trying to reply or forward an email thread

### ISSUE THREAD

**Issue by hadock** [nylas/N1#3013]
Issue -> i've updated the version from today on my iMac and i'm not able to reply or forward any message, i haven't update nylas already on my MacBook where everything seems to be fine.

OS: OSx Yosemite
Hw: iMac 2011
Nylas Version: 0.4.201
Pugins: i don't have plugins installed

**Comment by bengotow** [comment]
Hi @hadock thanks for reaching out - do you see anything happen? Do you know if this only happens if the selected email has attachments? (I believe there's a known issue with the beta that we're fixing today.)

**Comment by jackiehluo** [comment]
Closing this issue since it sounds like it should be fixed!

**Comment by hadock** [comment]
It happens all the time =(

nylas-env.js:302 Error: Assertion Failure: BEGIN called when an existing transaction is in-flight. Use DatabaseStore.inTransaction() to aquire transactions.
    at err (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:367:17)
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:71:37)
    at DatabaseStore._query (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:337:12)
    at DatabaseTransaction._query (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-transaction.js:25:28)
    at DatabaseTransaction.execute (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-transaction.js:57:17)
    at Queue._dequeue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/promise-queue/lib/index.js:148:26)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/promise-queue/lib/index.js:108:18
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:71:37)
    at Queue.add (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/promise-queue/lib/index.js:93:16)
    at DraftStore._finalizeAndPersistNewMessage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/draft-store.js:463:36)
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5) Object {promise: Promise}
