### ISSUE TITLE
Perpetual loading indicator in right pane

### ISSUE THREAD

**Issue by emadow** [nylas/N1#3072]
Many times, when clicking on an email message in the left pane, the right pane will perpetually show a loading indicator. I can't view the email until I double click the message and open it in a new window:

![loading](https://cloud.githubusercontent.com/assets/490190/20434584/667cabd8-ad76-11e6-93c0-37fa8f436051.gif)

##### Are there any related issues?
There doesn't seem to be

##### What operating system are you using?
MacOS Sierra

##### What version of N1 are you using?
Version 0.4.204-c4a286f (0.4.204-c4a286f)

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
There doesn't appear to be any pattern

**Comment by jackiehluo** [comment]
Oh, no! Are there any error logs when that happens in Developer -> Toggle Developer Tools -> Console?

**Comment by emadow** [comment]
Indeed!

```
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:302

TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (/Applications/NylasN1.app/Contents/Resources/app.asar/node_modules/react/lib/DOMLazyTree.js:70:21)
    at
nylas-env.js:302 TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/DOMLazyTree.js:70:21)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Danger.js:42:19)
    at ReactCompositeComponentWrapper._replaceNodeWithMarkup (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:781:31)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:771:12)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:721:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:558:12)
    at Object.performUpdateIfNecessary (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:158:22)
    at runBatchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:151:21)
    at ReactReconcileTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:138:20)
    at ReactUpdatesFlushTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:138:20)
    at Object.flushBatchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:173:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:204:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:151:16)
    at Object.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.enqueueUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:201:22)
    at enqueueUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:25:16)
    at Object.enqueueSetState (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:210:5)
    at ViewOnGithubButton.ReactComponent.setState (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactComponent.js:64:16)
    at GithubStore.ViewOnGithubButton._onStoreChanged (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-view-on-github/lib/view-on-github-button.js:72:12)
    at EventEmitter.eventHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/modules/reflux-coffee.js:208:27)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at GithubStore.trigger (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/modules/reflux-coffee.js:220:30)
    at GithubStore._onMessageStoreChanged (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-view-on-github/lib/github-store.js:52:10)
    at EventEmitter.eventHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/modules/reflux-coffee.js:208:27)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at MessageStore.trigger (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/modules/reflux-coffee.js:220:30)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/message-store.js:362:26
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5) ```

**Comment by jackiehluo** [comment]
Hmmm, looks like it's a problem with the View on Github plugin! Can you disable that and see if it works?

**Comment by emadow** [comment]
that did it! thanks @jackiehluo !!

**Comment by jackiehluo** [comment]
Cool, thanks for reporting! We'll take a look at the plugin and see what broke. 👍
