### ISSUE TITLE
Reply in a thread won't load content

### ISSUE THREAD

**Issue by tommykiser** [nylas/N1#3075]
I have a message that won't open and display the content. I just get the loading spinner forever. The thread is fine for a lot of back and forth, then there's a reply that won't load, and all the messages after that have the same issue. 

I've pulled up the message in the Outlook web client, and it renders fine. The only funky character in that reply is a winky-face emoji, maybe that is tripping things up? All the subsequent messages would have that same character showing in the previous thread display, so would make sense if that was breaking everything.

##### Are there any related issues?
This sounds similar, though I don't have any attachments on the message, so likely a different cause:
https://github.com/nylas/N1/issues/3059
...

##### What operating system are you using?
OSX 10.11.6
...

##### What version of N1 are you using?
Version 0.4.204-c4a286f (0.4.204-c4a286f)
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Only some of the built-in plugins that ship with Nylas:
Activity List
Emoji Picker
Mail Merge
Scheduler
Encryption
Link Tracking
Open Tracking
Send Later
Send Reminders
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only have one example of the problem, and it's with my Exchange account. Not sure if the same issue would happen on Gmail or not.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![screen shot 2016-11-18 at 11 11 19 am](https://cloud.githubusercontent.com/assets/2207389/20443031/ede8a4c4-ad7f-11e6-8015-2e8889b18f04.png)

--

Cheers,
-Tommy

**Comment by jackiehluo** [comment]
If you go to Developer -> Toggle Developer Tools -> Console, what do you see?

**Comment by tommykiser** [comment]
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:302 Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Error (native)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/message-item-body.js:188:114
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at MessageItemBody._mergeBodyWithFiles (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/message-item-body.js:187:23)
    at MessageItemBody._mergeBodyWithFiles (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/message-item-body.js:3:59)
    at MessageItemBody._renderBody (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/message-item-body.js:106:27)
    at MessageItemBody._renderBody (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/message-item-body.js:3:59)
    at MessageItemBody.render (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/message-item-body.js:99:16)
    at MessageItemBody.render (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/message-item-body.js:3:59)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:796:32)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:819:34)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:743:36)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:721:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:110:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:215:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:314:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:301:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:718:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:110:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:215:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:314:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:301:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:718:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:110:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:215:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:314:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:301:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:718:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:751:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:721:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:751:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:721:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:110:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:215:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:314:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:301:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:718:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:110:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:215:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:314:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:301:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:718:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:110:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:215:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:314:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:301:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:718:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:751:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:721:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:110:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:215:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:314:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:301:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:718:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:110:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:215:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:314:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:301:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:718:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:751:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:721:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:126:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:751:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:721:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:558:12)
    at Object.performUpdateIfNecessary (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:158:22)
    at runBatchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:151:21)
    at ReactReconcileTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:138:20)
    at ReactUpdatesFlushTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:138:20)
    at Object.flushBatchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:173:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:204:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:151:16)
    at Object.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.enqueueUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:201:22)
    at enqueueUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:25:16)
    at Object.enqueueSetState (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:210:5)
    at MessageList.ReactComponent.setState (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactComponent.js:64:16)
    at MessageList._onChange (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/message-list.js:610:19)
    at MessageStore.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/message-list/lib/message-list.js:3:59)
    at EventEmitter.eventHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/modules/reflux-coffee.js:208:27)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at MessageStore.trigger (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/modules/reflux-coffee.js:220:30)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/message-store.js:362:26
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5) ObjectpluginIds: Array[1]promise: Promise__proto__: Objectmodule.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:302
