### ISSUE TITLE
Nylas won't startup - infinite lookp of QuerySubscription errors

### ISSUE THREAD

**Issue by tcolar** [nylas/N1#3084]
Nylas won't fully startup, the UI shows up, the menu is responsive but nothing else works : no email showed, clicking menu items does nothing.

Starting it in a terminal window I see it's stuck in an infinite error loop of this:
```
2016-11-22 13:13:06.388 Nylas N1[14349:7363776] Error: QuerySubscription: Applied all changes and result set contains duplicate IDs.
    at QuerySubscription._createResultAndTrigger (/src/flux/models/query-subscription.es6:270:15)
    at _fetchMissingModels.then.models (/src/flux/models/query-subscription.es6:248:14)
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
2016-11-22 13:13:06.395 Nylas N1[14349:7363776] Error: QuerySubscription: Applied all changes and result set contains duplicate IDs.
    at QuerySubscription._createResultAndTrigger (/src/flux/models/query-subscription.es6:270:15)
    at _fetchMissingModels.then.models (/src/flux/models/query-subscription.es6:248:14)
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
2016-11-22 13:13:06.395 Nylas N1[14349:7363776] undefined
2016-11-22 13:13:06.395 Nylas N1[14349:7363776] undefined
2016-11-22 13:13:06.396 Nylas N1[14349:7363776] undefined
```

##### What operating system are you using?
Mac OS 10.12

##### What version of N1 are you using?
Latest

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't think so

**Comment by franzos** [comment]
I have the same issue with 0.4.400. Reverted to [0.4.204](https://github.com/nylas/N1/releases/tag/0.4.204).
