### ISSUE TITLE
script/bootstrap Error: Cannot find module '../src/request'

### ISSUE THREAD

**Issue by GabLeRoux** [nylas/N1#3107]
I can't get manage to compile this project on arch linux.

I tried installing `n1` from the aur, but I'm still stuck with this:
https://github.com/nylas/sync-engine/issues/319

I gave a try to `n1-git`, I also tried manually from git and it does the same. I followed compilation instructions from here:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=n1-git

It fails when I run the bootstrap script with the following error:

## complete log

```

-- Running npm install in ./build with system config --
npm WARN nylas-build@ No license field.

-- Running npm install in ./apm with apm config --
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@2.0.4: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global coffee-script@1.9.0 should be installed with -g
npm WARN prefer global npm@2.13.3 should be installed with -g

> keytar@3.0.2 install /run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/keytar
> node-gyp rebuild

make: Entering directory '/run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/keytar/build'
  CXX(target) Release/obj.target/keytar/src/main.o
  CXX(target) Release/obj.target/keytar/src/keytar_posix.o
  SOLINK_MODULE(target) Release/obj.target/keytar.node
  COPY Release/keytar.node
make: Leaving directory '/run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/keytar/build'

> oniguruma@5.1.2 install /run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/oniguruma
> node-gyp rebuild

make: Entering directory '/run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/oniguruma/build'
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  AR(target) Release/obj.target/oniguruma.a
  COPY Release/oniguruma.a
  CXX(target) Release/obj.target/onig_scanner/src/onig-cache.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-result.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-reg-exp.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner-worker.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-searcher.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-string-context.o
  CXX(target) Release/obj.target/onig_scanner/src/unicode-utils-posix.o
  SOLINK_MODULE(target) Release/obj.target/onig_scanner.node
  COPY Release/onig_scanner.node
make: Leaving directory '/run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/oniguruma/build'

> git-utils@4.1.4 install /run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/git-utils
> node-gyp rebuild

make: Entering directory '/run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/git-utils/build'
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/annotated_commit.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/attr.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/attr_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/attrcache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/blame.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/blame_git.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/blob.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/branch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/buf_text.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/buffer.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/cache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/checkout.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/cherrypick.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/clone.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/commit.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/commit_list.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/config.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/config_cache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/config_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/crlf.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/curl_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/date.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/delta-apply.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/delta.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/describe.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_driver.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_patch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_print.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_stats.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_tform.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/diff_xdiff.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/errors.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fetch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fetchhead.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/filebuf.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fileops.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/filter.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/fnmatch.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/global.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/graph.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/hash.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/hashsig.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/ident.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/ignore.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/index.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/indexer.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/iterator.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/merge.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/merge_file.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/message.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/mwindow.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/netops.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/notes.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/object.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/object_api.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb_loose.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb_mempack.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/odb_pack.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/oid.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/oidarray.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/openssl_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pack-objects.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pack.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/path.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pathspec.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pool.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/posix.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/pqueue.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/push.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/rebase.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refdb.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refdb_fs.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/reflog.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refs.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/refspec.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/remote.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/repository.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/reset.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/revert.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/revparse.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/revwalk.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/settings.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/sha1_lookup.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/signature.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/socket_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/sortedcache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/stash.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/status.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/stransport_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/strmap.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/submodule.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/sysdir.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tag.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/thread-utils.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tls_stream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/trace.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transaction.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transport.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tree-cache.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tree.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/tsort.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/util.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/vector.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/zstream.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/auth.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/auth_negotiate.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/cred.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/cred_helpers.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/git.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/http.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/local.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/smart.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/smart_pkt.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/smart_protocol.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/ssh.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/transports/winhttp.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xdiffi.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xemit.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xhistogram.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xmerge.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xpatience.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xprepare.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/xdiff/xutils.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/hash/hash_generic.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/unix/map.o
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/unix/realpath.o
  AR(target) Release/obj.target/git2.a
  COPY Release/git2.a
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/adler32.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/crc32.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/deflate.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/inffast.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/inflate.o
../deps/libgit2/deps/zlib/inflate.c: In function ‘inflateMark’:
../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: left shift of negative value [-Wshift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/inftrees.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/trees.o
  CC(target) Release/obj.target/zlib/deps/libgit2/deps/zlib/zutil.o
  AR(target) Release/obj.target/zlib.a
  COPY Release/zlib.a
  CC(target) Release/obj.target/http_parser/deps/libgit2/deps/http-parser/http_parser.o
  AR(target) Release/obj.target/http_parser.a
  COPY Release/http_parser.a
  CXX(target) Release/obj.target/git/src/repository.o
  SOLINK_MODULE(target) Release/obj.target/git.node
  COPY Release/git.node
make: Leaving directory '/run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/git-utils/build'

> atom-package-manager@1.1.1 install /run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/atom-package-manager
> node ./script/download-node.js

module.js:472
    throw err;
    ^

Error: Cannot find module '../src/request'
  at Function.Module._resolveFilename (module.js:470:15)
  at Function.Module._load (module.js:418:25)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/node_modules/atom-package-manager/script/download-node.js:16:13)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.runMain (module.js:605:10)
  at run (bootstrap_node.js:420:7)
  at startup (bootstrap_node.js:139:9)
  at bootstrap_node.js:535:3

npm WARN n1-bundled-apm@ No license field.
npm ERR! Linux 4.8.10-1-ARCH
npm ERR! argv "/usr/bin/node" "/home/gableroux/.npm-global/bin/npm" "install"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.1.1 install: `node ./script/download-node.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.1.1 install script 'node ./script/download-node.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-node.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-package-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /run/media/gableroux/extdata/gableroux/repos/linux/N1/apm/npm-debug.log
```

```
 ls -la src | grep request
-rw-r--r--  1 gableroux users   853 Dec  1 17:43 multi-request-progress-monitor.es6
```

Not quite sure where this `../src/request` module is supposed to be found. but in fact, problem seems to by my node version I guess.

```
$ node --version               
v7.2.0

$ npm --version                                                                            
3.10.8

$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.2
```

##### Are there any related issues?

There are quite a few issues concerning `script/bootstrap`, but none of them fails to find '../src/request'

##### What operating system are you using?
```
uname -a
Linux zbookarch.local 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 GNU/Linux
```

##### What version of N1 are you using?
```
0.4.32.r987.gf35008d
```

**Comment by KevinMartin** [comment]
What version of node.js are you using?

Possibly related: https://github.com/nylas/N1/issues/3083#issuecomment-262292163

**Comment by GabLeRoux** [comment]
I updated my issue with the right infos

**Comment by GabLeRoux** [comment]
I ended up doing this:
```
# install nvm
sudo aura -A nvm

nvm install v6.9.1
unset NPM_CONFIG_PREFIX
nvm use --delete-prefix v9.6.1
```
```
node --version                
v6.9.1
```
```
./script/bootstrap 
```
That worked! :tada: 
```
./script/grunt build
```
> Done, without errors.
:sunglasses: :icecream: 
Thanks @KevinMartin !
