### ISSUE TITLE
Message attachment causing message not to load?

### ISSUE THREAD

**Issue by sachinag** [nylas/N1#3119]
Couldn't load a declined calendar invite

```
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:302 TypeError: path.extname is not a function
    at Object.shouldDisplayAsImage (/src/flux/models/utils.coffee:116:16)
    at files.filter.f (/internal_packages/attachments/lib/message-attachments.jsx:77:54)
    at Array.filter (native)
    at MessageAttachments.render (/internal_packages/attachments/lib/message-attachments.jsx:77:33)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:799:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:691:32)
    at ReactDOMComponent.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:691:32)
    at ReactDOMComponent.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:691:32)
    at ReactDOMComponent.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:691:32)
    at ReactDOMComponent.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:691:32)
    at ReactDOMComponent.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:691:32)
    at ReactDOMComponent.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:121:51)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:213:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:930:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:748:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:710:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:125:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:213:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:930:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:748:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:710:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:125:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:213:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:930:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:748:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:710:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:125:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:754:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:547:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:125:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:213:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:930:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:748:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:710:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:125:22)
    at Object.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:213:28)
    at ReactDOMComponent._updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:312:31)
    at ReactDOMComponent.updateChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:299:12)
    at ReactDOMComponent._updateDOMChildren (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:930:12)
    at ReactDOMComponent.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:748:10)
    at ReactDOMComponent.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:710:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:125:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:754:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:547:10)
    at Object.receiveComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:125:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:754:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:724:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:645:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:561:12)
    at Object.performUpdateIfNecessary (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:157:22)
    at runBatchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:150:21)
    at ReactReconcileTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at ReactUpdatesFlushTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.flushBatchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:206:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:153:16)
    at Object.enqueueUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:200:22)
    at enqueueUpdate (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:24:16)
    at Object.enqueueSetState (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:209:5)
    at MessageList.ReactComponent.setState (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactComponent.js:63:16)
    at MessageList._onChange (/internal_packages/message-list/lib/message-list.cjsx:413:6)
    at MessageStore.<anonymous> (/internal_packages/message-list/lib/message-list.cjsx:1:1)
    at EventEmitter.eventHandler (/src/flux/modules/reflux-coffee.coffee:167:18)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at MessageStore.trigger (/src/flux/modules/reflux-coffee.coffee:175:17)
    at /src/flux/stores/message-store.coffee:275:10
    at tryCatcher (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5) Objectmodule.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:302
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:302 TypeError: Cannot read property 'addEventListener' of null
    at /src/components/evented-iframe.cjsx:108:10
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/underscore/underscore.js:768:19 Objectmodule.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:302
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/components/evented-iframe.js:167 Uncaught TypeError: Cannot read property 'addEventListener' of null
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:331  45msec (5msec in agent): SELECT `Thread`.`data` FROM `Thread` WHERE `id` IN (SELECT `id` FROM `ThreadContact` WHERE `ThreadContact`.`value` = 'ben@nylas.com'  ORDER BY `ThreadContact`.`last_message_received_timestamp` DESC LIMIT 100)  ORDER BY `Thread`.`last_message_received_timestamp` DESC
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:331  1004msec: BEGIN IMMEDIATE TRANSACTION
```

**Comment by emorikawa** [comment]
Fixed by https://github.com/nylas/N1/commit/2821ef4a652b81deb68f141c6ea6e78ea4632fd0
