### ISSUE TITLE
Nylas N1 freezes at splash

### ISSUE THREAD

**Issue by ericscollins** [nylas/N1#3139]
##### Are there any related issues?

There does not appear to be.

##### What operating system are you using?
Ubuntu 16.10 64-bit

##### What version of N1 are you using?
v1.4.12

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

I've built N1 without issue, as far as I can tell, but when running the product, I get three Chrome windows featuring the N1 splash and two with the development tools pane open. In the console I get the following error:
`Error: Cannot find module 'debug/browser'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/home/eric/Downloads/N1/dist/nylas-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/src/module-cache.coffee:267:20)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/eric/Downloads/N1/dist/nylas-linux-x64/resources/app.asar/node_modules/debug-electron/index.js:1:129)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/eric/Downloads/N1/dist/nylas-linux-x64/resources/app.asar/node_modules/electron-spellchecker/lib/context-menu-builder.js:21:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)handleSetupError @ index.js:28`

Here is a screen capture as well:
![screenshot from 2016-12-29 15-38-25](https://cloud.githubusercontent.com/assets/21368543/21554609/f0380042-cdde-11e6-9a56-a67c7918710a.png)
Any ideas on how to resolve this?

**Comment by gurkerl83** [comment]
Hi, 
I ran into the same problem.

First - I executed ./script/bootstrap
Second - npm run build
Third - npm run start

-> Same problem - the module debug/browser was not available.

Then I tried installing debug by myself with

npm install debug - still the same error until I tried an older version started at debug version 2.2.0

I ran - npm install debug@2.2.0 which was actually working - N1 launched!

I tried to find out the reason why it is working with an older version of debug but  does not with the latest version (2.6.0).

For now I validated the version number up until 2.4.5 was working - 2.5.1 responded with this error. I ran N1 on a mac-os.

Maybe this helps.

Thanks!

**Comment by gurkerl83** [comment]
Note:
A temporary fix in order to support the latest version of debug is to checkout debug and add a .js file named browser.js in the root directory with the following content.

module.exports = require('./src/browser');

Thanks!

**Comment by oksas** [comment]
Working on a PR and ran into the same issue :( For now I just ran `npm install debug@2.4.5` as suggested and that issue went away. Thanks for sharing @gurkerl83 👍

**Comment by ericscollins** [comment]
Thanks @gurkerl83 , that worked for me too.
