### ISSUE TITLE
N1 Build failing with error "Failed at the atom-package-manager@1.1.1 install script 'node ./script/download-node.js' "

### ISSUE THREAD

**Issue by avanish0509** [nylas/N1#3150]
I'm trying to build N1 from source on a mac machine with OS X El Capitan (Version 10.11.6) with the help of **Getting Started** guide at  "https://github.com/nylas/N1/blob/master/CONTRIBUTING.md"  but it fails to build on my machine due to the error _Cannot find module '../src/request'_ 

Error log:
1. 
`atom-package-manager@1.1.1 install /Users/avanishyadav/N1/apm/node_modules/atom-package-manager
> node ./script/download-node.js

module.js:472
    throw err;
    ^`
2. 

`Error: Cannot find module '../src/request'
  at Function.Module._resolveFilename (module.js:470:15)
  at Function.Module._load (module.js:418:25)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/avanishyadav/N1/apm/node_modules/atom-package-manager/script/download-node.js:16:13)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.runMain (module.js:605:10)
  at run (bootstrap_node.js:420:7)
  at startup (bootstrap_node.js:139:9)
  at bootstrap_node.js:535:3`

**Comment by MooShoe** [comment]
+1

**Comment by MooShoe** [comment]
I solved it. You have to be running node 6 not 7.

**Comment by avanish0509** [comment]
Thanks MooShoe, I'll give it a go. Hopefully it works for me as well.
