### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [nylas/N1#3183]
##### Are there any related issues?

...

##### What operating system are you using?
...
linux
##### What version of N1 are you using?
...
Git Head
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

> atom-package-manager@1.1.1 install /home/solaraquarion/.cache/pacaur/n1-git/src/N1/apm/node_modules/atom-package-manager
> node ./script/download-node.js

module.js:472
    throw err;
    ^

Error: Cannot find module '../src/request'
  at Function.Module._resolveFilename (module.js:470:15)
  at Function.Module._load (module.js:418:25)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/solaraquarion/.cache/pacaur/n1-git/src/N1/apm/node_modules/atom-package-manager/script/download-node.js:16:13)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.runMain (module.js:605:10)
  at run (bootstrap_node.js:420:7)
  at startup (bootstrap_node.js:139:9)
  at bootstrap_node.js:535:3

n1-bundled-apm@ /home/solaraquarion/.cache/pacaur/n1-git/src/N1/apm
└── d@0.1.1  extraneous

npm WARN n1-bundled-apm@ No license field.
npm ERR! Linux 4.8.9-pf
npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.1.1 install: `node ./script/download-node.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.1.1 install script 'node ./script/download-node.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-node.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-package-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/solaraquarion/.cache/pacaur/n1-git/src/N1/apm/npm-debug.log
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by OJFord** [comment]
I'm seeing this too (it's why I haven't been able to test #3163 or #3164).

**Comment by jstejada** [comment]
hi all! Thanks for reporting.

When are you seeing this error specifically? What command are you using to run the build?

**Comment by ryneeverett** [comment]
> When are you seeing this error specifically? What command are you using to run the build?

`npm run build`
