### ISSUE TITLE
Cannot send email from Outlook.com account

### ISSUE THREAD

**Issue by goncalotomas** [nylas/N1#3190]
Every time I try to send out email from my Outlook.com account, regardless if its setup as an Exchange account or as a custom IMAP account, this happens: 

![error screen](http://i.imgur.com/uS9SRsR.png)

Here is the stack trace:
```
Sending failedError: Sending failed
    at NylasError (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:2:1)
    at APIError (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:14:5)
    at sendmail-client.es6:57:11
    at throw (<anonymous>)
    at step (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:191)
    at /private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:402
    at tryCatcher (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)Error
    at new APIError (/src/flux/errors.es6:28:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:29:25)
    at EventEmitter.eventHandler (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/internal_packages/worker-sync/lib/delta-processor.es6:140:13)
    at /internal_packages/worker-sync/lib/delta-processor.es6:78:12
    at next (<anonymous>)
    at step (/internal_packages/worker-sync/lib/delta-processor.es6:2:1)
    at /internal_packages/worker-sync/lib/delta-processor.es6:2:1
    at tryCatcher (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/private/var/folders/tb/8x4n21td127_szx39yj4ns180000gn/T/AppTranslocation/228D4D62-57F0-4CE9-8A64-C9A6A5E55A69/d/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```
##### Are there any related issues?

#3115, but I have a stable internet connection
##### What operating system are you using?
Latest version of Mac OS Sierra

##### What version of N1 are you using?
Version 1.0.8 (1.0.8)

##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
An Outlook.com account

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Trying to send out any email (with or without body, with or without attachments) fails. Receiving emails is fine.

**Comment by goncalotomas** [comment]
Still happening in 1.0.10.

**Comment by jstejada** [comment]
thanks for the report! I'm merging this into issue #3182
