### ISSUE TITLE
Sending Failed

### ISSUE THREAD

**Issue by scott-joe** [nylas/N1#3192]
### Are there any related issues?
>The only issue I could find similar to my own in open or closed issues was #893. But that was over a year ago, and the error logs didn't appear to match. It was claimed to be fixed during a patch as well.

### What operating system are you using?
>MacOS Sierra 10.12.2 (16C67)

### What version of N1 are you using?
>1.0.8 (1.0.8)

---

##### Do you have any third-party plugins installed? If so, which ones?
> No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
> Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?
> This is the 1st email I've sent from the app. It is reproducable in the sense that it happens every time I attempt to reply to this email.

_Initial Error_
![screenshot 2017-01-18 13 57 43](https://cloud.githubusercontent.com/assets/2026866/22078604/9383f574-dd86-11e6-95b5-18197edec0b0.png)

_Error details_
![screenshot 2017-01-18 13 57 53](https://cloud.githubusercontent.com/assets/2026866/22078613/99f152da-dd86-11e6-9812-6f798b4a0d5a.png)

```log
Sending failedError: Sending failed
    at NylasError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:2:1)
    at APIError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:14:5)
    at sendmail-client.es6:57:11
    at throw (<anonymous>)
    at step (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:191)
    at /Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:402
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)Error
    at new APIError (/src/flux/errors.es6:28:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:29:25)
    at EventEmitter.eventHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/internal_packages/worker-sync/lib/delta-processor.es6:140:13)
    at /internal_packages/worker-sync/lib/delta-processor.es6:78:12
    at next (<anonymous>)
    at step (/internal_packages/worker-sync/lib/delta-processor.es6:2:1)
    at /internal_packages/worker-sync/lib/delta-processor.es6:2:1
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by RawDawg** [comment]
I have the same issue with the same error log on 1.0.9, macOS 10.12.2, but also for custom IMAP accounts.

**Comment by adnanoner** [comment]
I have the same error Mac OS 10.12.2 (16C67), for gmail accounts. Let me know if I can help to debug or send a log.

**Comment by treyreynolds** [comment]
Wanted to chime in to say that I am also seeing the same error.
OS: macOS 10.11.5
Nylas Version: 1.0.8

Error Output:

`Sending failedError: Sending failed
    at NylasError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:2:1)
    at APIError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:14:5)
    at sendmail-client.es6:57:11
    at throw (<anonymous>)
    at step (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:191)
    at /Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:402
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)Error
    at new APIError (/src/flux/errors.es6:28:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:29:25)
    at EventEmitter.eventHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/internal_packages/worker-sync/lib/delta-processor.es6:140:13)
    at /internal_packages/worker-sync/lib/delta-processor.es6:78:12
    at next (<anonymous>)
    at step (/internal_packages/worker-sync/lib/delta-processor.es6:2:1)
    at /internal_packages/worker-sync/lib/delta-processor.es6:2:1
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)`

**Comment by tomgobich** [comment]
Same error here when trying to send from custom IMAP/SMTP account over non SSL connection
macOS Version 10.12.2
Nylas Version 1.0.10 - Fresh install, just set it up - credentials & ports are correct

I have a gmail account attached that's sending just find, the custom IMAP only is having this error on send.

**Comment by light2yellow** [comment]
I experience the same error with a custom IMAP/SMTP account over SSL connection.
Sierra .2
1.0.11
Backtrace:
```
Sending failedError: Sending failed
    at NylasError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:2:1)
    at APIError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:14:5)
    at sendmail-client.es6:57:11
    at throw (<anonymous>)
    at step (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:191)
    at /Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:402
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)Error
    at new APIError (/src/flux/errors.es6:28:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:29:25)
    at EventEmitter.eventHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/internal_packages/worker-sync/lib/delta-processor.es6:140:13)
    at /internal_packages/worker-sync/lib/delta-processor.es6:78:12
    at next (<anonymous>)
    at step (/internal_packages/worker-sync/lib/delta-processor.es6:2:1)
    at /internal_packages/worker-sync/lib/delta-processor.es6:2:1
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by goncalotomas** [comment]
I reported #3190, seems to be identical but with an Outlook.com account.

**Comment by RawDawg** [comment]
Well, no answer or fix for almost a week. Also there are 741 open issues. I don’t think it’s wise to rely on this software right now. I’ll check back in a year or so.

**Comment by goncalotomas** [comment]
@RawDawg not really a fair assumption. Angular 2 has >900 open issues, and you can certainly say it has very active development.
What is really lacking here is someone from the development team to state if this is something that they are working on, or if it's going to be a while before a fix is released.

Maybe some random user with enough JS knowledge will open a pull request fixing this. That'd be great.

**Comment by RawDawg** [comment]
I’m not saying it is bad software or you shouldn’t use it, but that it’s not wise to **rely** on it. Missed mails or not being sure if my mails got sent can cost me my job. I think the concept is great, it’s just not ready right now.

**Comment by tomkeysers** [comment]
Having the same issue. Sending from custom IMAP account.

**Comment by jstejada** [comment]
thanks for the reports everyone! merging into duplicate issue #3192

**Comment by lumadelaplace** [comment]
Same issue too, sending from a custom IMAP account
