### ISSUE TITLE
Don't send from iCloud account

### ISSUE THREAD

**Issue by MicheleRB** [nylas/N1#3209]
##### Are there any related issues?

send from iCloud account

##### What operating system are you using?
Mac Sierra

##### What version of N1 are you using?
 latest
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Only iCloud

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Sending failedError: Sending failed
    at NylasError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:2:1)
    at APIError (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/errors.js:14:5)
    at sendmail-client.es6:57:11
    at throw (<anonymous>)
    at step (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:191)
    at /Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/src/sendmail-client.es6:3:402
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)Error
    at new APIError (/src/flux/errors.es6:28:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:29:25)
    at EventEmitter.eventHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/internal_packages/worker-sync/lib/delta-processor.es6:140:13)
    at /internal_packages/worker-sync/lib/delta-processor.es6:78:12
    at next (<anonymous>)
    at step (/internal_packages/worker-sync/lib/delta-processor.es6:2:1)
    at /internal_packages/worker-sync/lib/delta-processor.es6:2:1
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by MicheleRB** [comment]
duplicate issue
