### ISSUE TITLE
could not find module 'underscore-plus' in develop mode but ok in normal package 

### ISSUE THREAD

**Issue by Fortiskrito** [nylas/N1#342]
[30051:1102/193355:INFO:CONSOLE(108)] "Error while compiling /Users/xiaxin/.nylas/dev/packages/demo3/lib/main.cjsx", source: /Users/xiaxin/Documents/github/N1/src/cjsx.js (108)
[30051:1102/193355:INFO:CONSOLE(109)] "Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Users/xiaxin/Documents/github/N1/src/module-cache.coffee:273:20)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/xiaxin/.nylas/dev/packages/demo3/lib/main.cjsx:4:12)
  at Object.<anonymous> (/Users/xiaxin/.nylas/dev/packages/demo3/lib/main.cjsx:23:4)
  at Module._compile (module.js:428:26)
  at compile (/Users/xiaxin/Documents/github/N1/src/cjsx.js:23:19)
  at Object.hotCompile (/Users/xiaxin/Documents/github/N1/src/cjsx.js:105:16)
  at Module.load (/Users/xiaxin/Documents/github/N1/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Users/xiaxin/Documents/github/N1/src/package.coffee:404:19)
  at /Users/xiaxin/Documents/github/N1/src/package.coffee:134:25
  at Package.module.exports.Package.measure (/Users/xiaxin/Documents/github/N1/src/package.coffee:117:13)
  at Package.module.exports.Package.load (/Users/xiaxin/Documents/github/N1/src/package.coffee:126:6)
  at PackageManager.module.exports.PackageManager.loadPackage (/Users/xiaxin/Documents/github/N1/src/package-manager.coffee:435:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Users/xiaxin/Documents/github/N1/src/package-manager.coffee:418:6)
  at Atom.module.exports.Atom.startRootWindow (/Users/xiaxin/Documents/github/N1/src/atom.coffee:656:15)
  at Object.<anonymous> (/Users/xiaxin/Documents/github/N1/src/window-bootstrap.coffee:12:6)
  at Object.<anonymous> (/Users/xiaxin/Documents/github/N1/src/window-bootstrap.coffee:3:1)
  at Module._compile (module.js:428:26)
  at Object.requireCoffeeScript [as .coffee] (/Users/xiaxin/Documents/github/N1/src/coffee-cache.coffee:52:10)
  at Module.load (/Users/xiaxin/Documents/github/N1/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at window.onload (file:///Users/xiaxin/Documents/github/N1/static/index.js:75:25)
", source: /Users/xiaxin/Documents/github/N1/src/cjsx.js (109)

**Comment by bengotow** [comment]
Hi @Fortiskrito — when you create packages for N1, they need to contain a node_modules folder with their dependencies. Take a look at `N1-Github-Recipients` as an example. In it's `package.json` file, it declares `request` as a dependency. It needs to do that even though we also use `request` in the app itself (they can be deduped at runtime).

After updating `package.json`, you can install dependencies using APM:

`/Applications/Nylas\ N1.app/Contents/Resources/app/apm/bin/apm install`

**Comment by grinich** [comment]
@Fortiskrito Please re-open if you still have issues!
