### ISSUE TITLE
Unable to run specs

### ISSUE THREAD

**Issue by orthes** [nylas/N1#560]
I'm creating my first simple plugin for N1 (https://github.com/orthes/n1-send-and-archive), but I'm unable to run specs.

When I clicked ```Run Plugin Specs...``` button first time, it opened the specs window, but with errors because I didn't update my specs back then. I closed the window, rewrote the specs, but now when I click ```Run Plugin Specs...``` button and choose plugin directory, nothing happens. No new window and no sign of any activity or error in Developer Tools, Activity Window or Detailed Logs. Nothing happens.

And also when I try ```Run N1 Specs...``` nothing happens either.

I tried to restart N1, click reload button, even restart my whole computer. Nothing helped.

I'm running ```0.3.26-c1ce330``` version on OS X 10.11.1

**Comment by bengotow** [comment]
Hey @orthes — thanks for filing this. I'm trying to reproduce the issue but I haven't been able to yet. Can you do me a favor and try quitting N1 and running it like this from the Terminal?

`/Applications/Nylas\ N1.app/Contents/MacOS/Nylas --dev --enable-logging`

This runs the N1 application in developer mode, but the output from all of the app's processes will appear in the terminal window, including the "main process" which isn't shown in the developer tools in any of the app's windows.

Try running the specs after launching the app that way and let me know what happens!

**Comment by orthes** [comment]
Thanks! But with this command N1 doesn't open at all. Instead I get this:

```
Streaming log data to /var/folders/s9/ks0z0d493jx11w8wn_t3wth40000gp/T/Nylas-N1-21276.log
2015-12-03 20:57:57.220 Nylas[21276:478532] Cannot find module '/Users/pavel/src/browser/application'
2015-12-03 20:57:57.226 Nylas[21276:478532] Error: Cannot find module '/Users/pavel/src/browser/application'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at EventEmitter.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/browser/main.js:53:21)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
2015-12-03 20:57:57.226 Nylas[21276:478532] Cannot find module '/Users/pavel/src/browser/application'
2015-12-03 20:57:57.226 Nylas[21276:478532] Error: Cannot find module '/Users/pavel/src/browser/application'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at EventEmitter.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/browser/main.js:53:21)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by francois2metz** [comment]
I have the same issue. After some debug, it seems that the window is opened/loaded, but I can't see it :(

```
[5685:1215/022611:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Streaming log data to /tmp/Nylas-N1-5685.log
[5685:1215/022611:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[5685:1215/022611:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[5685:1215/022611:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[5685:1215/022611:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[5721:1215/022611:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[5685:1215/022611:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[5685:1215/022611:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[5685:1215/022611:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[5685:1215/022611:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
App load time: 504ms
[5726:1215/022611:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[5685:1215/022613:INFO:CONSOLE(118)] "Streaming log data to /tmp/Nylas-N1-5685.5721.log", source: /home/francois/dev/N1/src/error-logger.js (118)
[5685:1215/022613:INFO:CONSOLE(118)] "Streaming log data to /tmp/Nylas-N1-5685.5726.log", source: /home/francois/dev/N1/src/error-logger.js (118)
[5685:1215/022619:INFO:CONSOLE(145)] "Long Polling Connection: Starting for account cs9mcw9e0tpetk57vs75tfxfz, token mSi7XrtemWQYeBO7d1fiKxAYMr5AmY, with cursor dtcvyjx4rmux2pagv3gsm8s0r", source: /home/francois/dev/N1/internal_packages/worker-sync/lib/nylas-long-connection.coffee (145)
[5685:1215/022619:INFO:CONSOLE(11)] "Window load time: 7915ms", source: file:///home/francois/dev/N1/static/index.js (11)
[5685:1215/022620:INFO:CONSOLE(311)] "%c %cSCAN TABLE%c Folder for %cSELECT%c %c`Folder`%c.%c`data`%c %cFROM%c %c`Folder`%c   ", source: /home/francois/dev/N1/src/flux/stores/database-store.coffee (311)
[5685:1215/022620:INFO:CONSOLE(311)] "%c %cSCAN TABLE%c Label for %cSELECT%c %c`Label`%c.%c`data`%c %cFROM%c %c`Label`%c   ", source: /home/francois/dev/N1/src/flux/stores/database-store.coffee (311)
WindowManager: Preparing a new 'composer' window
[5865:1215/022624:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[5685:1215/022624:INFO:CONSOLE(11)] "Window load time: 12668ms", source: file:///home/francois/dev/N1/static/index.js (11)
[5685:1215/022626:INFO:CONSOLE(118)] "Streaming log data to /tmp/Nylas-N1-5685.5865.log", source: /home/francois/dev/N1/src/error-logger.js (118)
WindowManager: Preparing a new 'composer' window
[5685:1215/022632:INFO:CONSOLE(11)] "Window load time: 8035ms", source: file:///home/francois/dev/N1/static/index.js (11)
[5925:1215/022632:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[5685:1215/022634:INFO:CONSOLE(118)] "Streaming log data to /tmp/Nylas-N1-5685.5925.log", source: /home/francois/dev/N1/src/error-logger.js (118)
[5685:1215/022640:INFO:CONSOLE(11)] "Window load time: 7875ms", source: file:///home/francois/dev/N1/static/index.js (11)
[5685:1215/022649:INFO:CONSOLE(145)] "Long Polling Connection: Starting for account cs9mcw9e0tpetk57vs75tfxfz, token mSi7XrtemWQYeBO7d1fiKxAYMr5AmY, with cursor dtcvyjx4rmux2pagv3gsm8s0r", source: /home/francois/dev/N1/internal_packages/worker-sync/lib/nylas-long-connection.coffee (145)
```

**Comment by orthes** [comment]
Updating to ```0.3.32-b11131d``` fixed my problem. Thank you guys for the great app. Keep up the good work :+1:

**Comment by francois2metz** [comment]
Same for me. It works now.
