### ISSUE TITLE
Unable to find 'react' (for filter plugin)

### ISSUE THREAD

**Issue by zellwk** [nylas/N1#636]
Hello, I installed the filter plugin, but it doesn't seem to work. Here's the error message in the console: 

~~~
Cannot find module 'react' Error: Cannot find module 'react'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/module-cache.js:373:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/zellwk/.nylas/packages/N1-Filters/lib/filters.coffee:1:9)
    at Object.<anonymous> (/Users/zellwk/.nylas/packages/N1-Filters/lib/filters.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/zellwk/.nylas/packages/N1-Filters/lib/main.coffee:5:11)
    at Object.<anonymous> (/Users/zellwk/.nylas/packages/N1-Filters/lib/main.coffee:5:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:689:27)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:196:34
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:172:15)
    at Package.module.exports.Package.load (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:186:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:463:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:440:14)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startRootWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:693:21)
    at Object.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/window-bootstrap.js:18:12)
    at Object.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/window-bootstrap.js:29:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js:60:3)
    at window.onload (file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js:100:5)(anonymous function) @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:207
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:283 Cannot find module 'react'
~~~

**Comment by zellwk** [comment]
Sorry, discovered a previous issue after searching. #582. Closing this to prevent duplication
