### ISSUE TITLE
N1 doesn't start anymore

### ISSUE THREAD

**Issue by Birssan** [nylas/N1#730]
Hello,

I booted my computer this morning (Ubuntu 14.04 LTS), and surprise, N1 does not start anymore...

I tried to start it in the terminal here is the error...

```
Streaming log data to /tmp/Nylas-N1-9031.log
EACCES: permission denied, open '/usr/share/nylas/config.cson'
Error: EACCES: permission denied, open '/usr/share/nylas/config.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:140:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/usr/share/nylas/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at Object.module.exports.writeFileSync (/usr/share/nylas/resources/app.asar/node_modules/season/lib/cson.js:224:17)
    at Config.module.exports.Config.loadUserConfig (/usr/share/nylas/resources/app.asar/src/config.js:468:14)
    at Config.module.exports.Config.load (/usr/share/nylas/resources/app.asar/src/config.js:440:12)
    at new Application (/usr/share/nylas/resources/app.asar/src/browser/application.js:95:19)
    at createApplication (/usr/share/nylas/resources/app.asar/src/browser/application.js:47:16)
    at Function.module.exports.Application.open (/usr/share/nylas/resources/app.asar/src/browser/application.js:50:9)
    at EventEmitter.<anonymous> (/usr/share/nylas/resources/app.asar/src/browser/main.js:46:19)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
ErrorReporter: Shipping Logs. Exception occurred
/usr/share/nylas/resources/app.asar/src/nylas-private-ship-logs-task
/usr/share/nylas/resources/app.asar/src/task.js:39
        userAgent: navigator.userAgent
                   ^

ReferenceError: navigator is not defined
    at new Task (/usr/share/nylas/resources/app.asar/src/task.js:39:20)
    at Function.module.exports.Task.once (/usr/share/nylas/resources/app.asar/src/task.js:17:14)
    at ErrorReporter.module.exports.ErrorReporter.runShipLogsTask (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:136:17)
    at ErrorReporter.module.exports.ErrorReporter.shipLogs (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:102:14)
    at ErrorReporter.module.exports.ErrorReporter.reportError (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:87:10)
    at ErrorReporter.module.exports.ErrorReporter.onDidThrowError (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:48:10)
    at ErrorLogger.<anonymous> (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:30:59)
    at ErrorLogger.module.exports.ErrorLogger.notifyExtensions (/usr/share/nylas/resources/app.asar/src/error-logger.js:162:26)
    at process.<anonymous> (/usr/share/nylas/resources/app.asar/src/error-logger.js:190:14)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)
```
The log created at /tmp/Nylas-N1-9031.log is empty...

**Comment by bengotow** [comment]
Hi—it sounds like the app is trying to use `/usr/share/nylas/` as your configuration directory. It should be `~/.nylas`.  Are you running a version you downloaded from the N1 website or got through an update? Might be related to the recent configDirPath change? (cc @emorikawa)

**Comment by Birssan** [comment]
Well yes I changed my NYLAS_HOME env var to /usr/share/nylas when I had this error #492 
I worked until yesterday, now I just can't start it anymore. And I downloaded the deb file from the official website.
