### ISSUE TITLE
Old bug again. Nylas quits unexpectedly after closing main window and reopening using OSX dock icon

### ISSUE THREAD

**Issue by akizor** [nylas/N1#801]
Old bug #481 is here again.

OS X El Capitan
v10.11.1

Nylas
Version 0.3.32-b11131d (0.3.32-b11131d)

**Comment by jstejada** [comment]
hey @akizor thanks for reporting! I haven't been able to replicate, would you mind sending me the logs from the developer console? `Developer -> Toggle Developer Tools`

**Comment by akizor** [comment]
```
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:206 Failed to load package named 'N1-Filters'
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:207 Error: Cannot find module 'react'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/module-cache.js:373:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (<anonymous>:1:9)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (<anonymous>:5:11)
    at Object.<anonymous> (<anonymous>:5:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:690:27)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:197:34
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:173:15)
    at Package.module.exports.Package.load (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:187:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:463:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:440:14)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startRootWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:691:21)
    at Object.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/window-bootstrap.js:20:12)
    at Object.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/window-bootstrap.js:31:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js:63:3)
    at window.onload (file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js:103:5)
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:208 Cannot find module 'react' Error: Cannot find module 'react'(…)
```

this repeats 3 times

**Comment by akizor** [comment]
Suddenly, it works now. I'm closing this!

**Comment by mbilker** [comment]
That error is normal. The `N1-Filters` module is not ready for production usage yet and is prone to these errors. I would suggest removing it and waiting until it is improved. It is currently In Development according to https://trello.com/c/7GHlWEWO.

**Comment by akizor** [comment]
I think this should be a heads-up for other people that are experiencing this and credit it for other issues. Dont think some of them will have time to check trello or view development process of n1. Consumer oriented i mean.

Btw, thank you for answering

**Comment by mbilker** [comment]
@akizor yeah. N1 is still not completely stable yet. I find it useful for almost all my day-to-day stuff. I don't compose a lot of emails, but I know many people who do and need it to work properly.

My biggest complaint is how N1 handles multiple thread participants and defaults to Reply to All instead of Reply to the sender.

**Comment by akizor** [comment]
Also, as for my initial issue report it seems that fully close nylas n1 solved the issue. This means forcing process kill from activity monitor.

**Comment by akizor** [comment]
@mbilker Columbus whould be proud (bad jke here)
